Regex search tables
nasa/openmct pull request #2956
Opened 2020-04-21 23:15 UTC by deeptailor

Fixes #2534 

## Author Checklist

- Changes address original issue? Yes
- Unit tests included and/or updated with changes? N/A
- Command line build passes? Yes
- Changes have been smoke-tested? Yes

Styling done and approved by @charlesh88

2020-04-22 00:08 UTC, charlesh88 requested changes
Running locally with a SWG in a Telemetry Table, I'm finding that after I enable regex and click in the input, it's not displaying the first character I type - but the field does think there's something in it.
![Screen Shot 2020-04-21 at 5 07 29 PM](https://user-images.githubusercontent.com/1056412/79926769-9c8c8300-83f2-11ea-9288-fb477025e8e4.png)

So I have to type "/" twice to get one to appear - or click on an active thing outside the input, like another regex button or even the Inspector splitter. I'm also seeing weird stuff with the Backspace key: putting the cursor to the right of what looks like one "/" and hitting Backspace doesn't work - but backspacing again does work.

2020-04-22 04:09 UTC, deeptailor commented
@charlesh88 - thanks for catching this. I fixed the issue you describe

2020-05-05 19:14 UTC, deeptailor commented
@charlesh88 - I fixed the issue you described, could you approve the changes?

2020-05-07 23:05 UTC, davetsay commented
Looks good. I have a couple comments and questions.

- / \\ / results in console error (forward slash, back slash, forward slash)
```
FilteredTableRowCollection.js?25a5:64 Uncaught SyntaxError: Invalid regular expression: /swg \/: \ at end of pattern
    at new RegExp (<anonymous>)
    at FilteredTableRowCollection.setColumnRegexFilter (FilteredTableRowCollection.js?25a5:64)
    at VueComponent.filterChanged (table.vue?5cb1:559)
    at Proxy.boundFn (vue.js?ba4c:194)
    at complete (index.js?45e9:7697)
    at delayed (index.js?45e9:7707)
```

- filter breaks if i 1) enter a valid filter (non-regex), 2) add a character to match nothing, 3) remove the character in step 2. I'm unsure if this is a known issue.
![cannot unfilter](https://user-images.githubusercontent.com/3614296/81352876-7fa3b100-907c-11ea-99bb-3bea14c56aea.gif)

- is it possible to have the user click the regex button XOR type the open and close forward slashes? I understand the slashes are required to identify a valid regex expression. Obviously it would take more work but using vscode as an example - regex search does not require open close slashes and will alert the user for malformed regex expressions.
![image](https://user-images.githubusercontent.com/3614296/81352585-ca70f900-907b-11ea-8d0c-3b153db02d16.png)

2020-05-07 23:06 UTC, akhenry requested changes
Approach looks good to me. We need some tests though.

2020-05-07 23:06 UTC, akhenry commented on src/plugins/telemetryTable/components/table.vue
> +            return (string.length > 2 && string[0] === '/' && string[string.length - 1] === '/')
👍  Hehe, I'd have used a regex to test if it was a regex, but this approach is way more performant 😄

2020-05-08 18:03 UTC, davetsay approved these changes
## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | N/A |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |

2020-05-08 18:05 UTC, davetsay submitted a review, later dismissed

2020-05-15 20:56 UTC, charlesh88 submitted a review, later dismissed
LGTM

2020-07-13 19:45 UTC, deeptailor commented
@akhenry - Fixed the conflict

2020-09-11 23:31 UTC, akhenry commented
@deeptailor Just waiting for tests in order to merge this into master.

2020-12-21 22:18 UTC, deeptailor commented
@akhenry - Sorry for the delay on this branch, i added some tests and should be good to go

2021-05-06 00:40 UTC, akhenry approved these changes

2021-05-06 00:49 UTC, akhenry commented
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)

2021-05-06 00:50 UTC, merged

2026-08-05 01:46 UTC, RadotJar commented
>     * is it possible to have the user click the regex button XOR type the open and close forward slashes? I understand the slashes are required to identify a valid regex expression. Obviously it would take more work but using vscode as an example - regex search does not require open close slashes and will alert the user for malformed regex expressions.

Was there any followup on this? Would be a nice improvement to user experience if one didn't have to write the slashes at start and end