WIP: Notebook saved link
nasa/openmct pull request #2998
Opened 2020-05-01 20:53 UTC by nikhilmandlik

resolves: #2860

2020-05-05 21:36 UTC, charlesh88 commented
I tweaked the click to view message and pushed that up. LGTM and GTG.

2020-12-18 18:25 UTC, deeptailor requested changes
Just a couple of changes

2020-12-18 18:25 UTC, deeptailor commented on src/api/notifications/NotificationAPI.js
> +     * @param {Object} options
Need more info on what this options object can include

2020-12-18 18:25 UTC, deeptailor commented on src/api/notifications/NotificationAPI.js
> +     * @param {Object} options
same comment as above

2020-12-18 18:25 UTC, deeptailor commented on src/api/notifications/NotificationAPI.js
> +    error(message, options = {}) {
same comment as above

2021-01-04 17:52 UTC, deeptailor commented
@nikhilmandlik - Just have a few questions/comments

2021-01-21 21:36 UTC, deeptailor approved these changes
LGTM

2021-01-21 21:36 UTC, deeptailor commented
@nikhilmandlik  - This PR is good to merge, just need to fix some conflicts

2021-02-17 18:27 UTC, akhenry commented
@deeptailor  Looks like this is good to merge?

2021-02-17 19:16 UTC, deeptailor approved these changes
LGTM

2021-02-17 19:16 UTC, merged