Update the versioning process to include publishing the package to np…
nasa/openmct pull request #3354
Opened 2020-09-03 18:37 UTC by shefalijoshi

…mjs registry

2020-09-04 04:03 UTC, davetsay requested changes
I think there is one line that can be removed. Looks fine otherwise.

I'm curious, also @akhenry , @deeptailor , why don't we use `$ npm version`? It integrates with git  either by versioning based off of git tags or by pushing version commit and tags to git.

2020-09-11 18:04 UTC, shefalijoshi commented on docs/src/process/version.md
> +  5. Publish the release.
Ah yes. This publish is for github. The next one is for npm.

2020-09-11 23:34 UTC, akhenry approved these changes

2020-09-14 19:22 UTC, davetsay approved these changes
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | N/A |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |

2020-09-14 19:23 UTC, merged