Quick idea on a splash screen that will not increase load time
nasa/openmct pull request #3376
Opened 2020-09-15 22:22 UTC by deeptailor

This is a quick proto of us including a splash screen so users don't see css styles loading in-front of their eyes.

It adds almost no load time.

@charlesh88 @akhenry thoughts?

2020-09-25 23:21 UTC, charlesh88 commented
We really need this, the app has been looking very bad while loading. 

I've pushed some changes:

2020-09-28 17:08 UTC, deeptailor reviewed
Removing comment, disregard

2020-09-28 17:08 UTC, deeptailor commented on src/styles/vue-styles.scss
> +}
can we add this to the bottom of the file? so we can be sure its loaded fully

2020-09-28 17:10 UTC, deeptailor commented
@akhenry - Just needs your approval (or rejection 😄 )

2020-10-23 16:22 UTC, deeptailor commented
@akhenry - Thoughts on this?

2020-10-29 00:31 UTC, akhenry approved these changes
This looks good to me. I do notice that glyphs don't load until after the splash screen has been hidden, but I guess that's because they are resolved asynchronously, and only after the stylesheets have loaded.

2020-10-29 00:35 UTC, akhenry requested changes
Just needs a link to an issue.

2020-11-05 18:10 UTC, deeptailor commented
Closes #3502

2020-11-05 18:11 UTC, deeptailor commented
@akhenry Added an issue

2020-11-06 21:57 UTC, akhenry approved these changes

2020-11-06 21:58 UTC, akhenry commented
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - small non-code change
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

2020-11-06 21:58 UTC, merged