[LocalTimeSystem] Plugin tests
nasa/openmct pull request #3478
Opened 2020-10-29 18:30 UTC by jvigliotta

Added test spec for local time system.

closes #3477 

## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? By its nature
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes

2020-11-10 05:50 UTC, davetsay requested changes
The tests are fine. Is it possible to test at the plugin level though?

```
openmct = createOpenMct();
openmct.install(openmct.plugins.LocalTimeSystem());
```

2020-12-17 18:14 UTC, jvigliotta commented
@davetsay added plugin level tests

2020-12-17 21:11 UTC, davetsay requested changes
couple minor fixes

2020-12-17 21:11 UTC, davetsay commented on src/plugins/localTimeSystem/pluginSpec.js
> +        localTimeSystem = openmct.time.timeSystem('local', {
better to use `LOCAL_SYSTEM_KEY ` as you've defined

2020-12-17 21:11 UTC, davetsay commented on src/plugins/localTimeSystem/pluginSpec.js
> +            let local = timeSystems.find(ts => ts.key === 'local');
better to use `LOCAL_SYSTEM_KEY ` as you've defined

2020-12-17 21:11 UTC, davetsay commented on src/plugins/localTimeSystem/pluginSpec.js
> +            expect(openmct.time.timeSystem().key).toBe('local');
better to use `LOCAL_SYSTEM_KEY ` as you've defined

2020-12-17 21:11 UTC, davetsay commented on src/plugins/localTimeSystem/pluginSpec.js
> +            console.log(formatter);
remove `console.log`

2020-12-18 18:37 UTC, davetsay approved these changes
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | Y |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |

2020-12-18 18:38 UTC, merged