Adding a new Status API to Open MCT
nasa/openmct pull request #3479
Opened 2020-10-29 22:23 UTC by deeptailor

Adding a new Status API to allow developers to add statuses to domainObjects. Use cases at the moment include 

1. Default Notebook
2. Missing Object
3. Suspect DomainObjects

Future use cases could include flagging domainObjects as favorites etc

2020-10-30 00:10 UTC, davetsay commented on src/api/status/StatusAPISpec.js
> +
remove newline

2020-10-30 00:25 UTC, davetsay commented
Awesome work @deeptailor

2020-10-30 19:45 UTC, akhenry requested changes
@deeptailor I think this looks really great, a nice clean approach which solves a bunch of problems.

I do think that objects are going to need to have multiple statuses simultaneously, (eg. a notebook could be both the default notebook and a user favorite, so they can find it quickly).

Perhaps we could change `get` and `set` so that it accepts a key and value?

For convenience we probably also want observers to be able to only listen to a particular status (eg. tell me when this notebook becomes the default notebook).

2020-11-13 00:06 UTC, merged

2020-11-24 19:56 UTC, akhenry commented
@deeptailor I think we need to address the need for multiple statuses ASAP. eg. A notebook can be both the default notebook and be missing.