[Testing] [Notebook] fix failing notebook tests from three-dot-menu-proto
nasa/openmct pull request #3577
Opened 2020-12-03 23:15 UTC by nikhilmandlik

### Resolves: 
resolves: #3463 [Testing] [Notebook] fix failing notebook tests from three-dot-menu-proto 

### Author Checklist:
Check | Passed
-- | --
Changes address original issue? | Y
Unit tests included and/or updated with changes? | Y
Command line build passes? | Y
Changes have been smoke-tested? | Y

2020-12-04 18:54 UTC, davetsay requested changes
Thanks for fixing tests. Made a couple minor comments. Also, this isn't in your changes, but it might be best to move the var definitions inside the describe block scope. I don't know exactly if it makes a difference in the way jasmine picks up test files, but at the very least for consistency with other Spec file format.

2020-12-04 18:54 UTC, davetsay commented on src/plugins/notebook/pluginSpec.js
> +            // console.log('clickSnapshotIndicator', indicator);
remove console log

2020-12-04 18:54 UTC, davetsay commented on src/plugins/notebook/pluginSpec.js
> +            expect(success).toBe(true);
Up to you but to me this is clearer.
```suggestion
            expect(isExpandedBefore).toBeFalse();
            expect(isExpandedAfterFirstClick).toBeTrue();
            expect(isExpandedAfterSecondClick).toBeFalse();
```

2020-12-04 18:54 UTC, davetsay commented on src/plugins/notebook/pluginSpec.js
> +            expect(success).toBe(true);
see next comment about explicit expects

2020-12-11 17:36 UTC, shefalijoshi approved these changes
LGTM
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

2020-12-18 18:22 UTC, davetsay approved these changes

2020-12-18 18:26 UTC, merged