[Navigation Tree] Move "nav up" arrow down one item
nasa/openmct pull request #3581
Opened 2020-12-04 23:17 UTC by jvigliotta

Moved the "nav up" arrow to show on the item below where it was previously. This will make it so it will nave up to the item ABOVE the item with the "nav up" arrow. Updated object path as well since it's built using the ancestors. Added the icon, but it will need more styling and correct css structure.

### Author Checklist
Check | Passed
-- | --
Changes address original issue? | Y
Unit tests included and/or updated with changes? | N/A
Command line build passes? | Y
Changes have been smoke-tested? | Y
Testing instructions included? | Y

closes #3575 (after @charlesh88 changes)

2020-12-18 18:30 UTC, charlesh88 requested changes
Current approach ends up hiding the nav-to-parent button that normally is visible to the left of the main view's object label:

<img width="872" alt="Screen Shot 2020-12-18 at 10 24 11 AM" src="https://user-images.githubusercontent.com/1056412/102648168-e1042600-411b-11eb-9f49-859a157ebf25.png">

This needs to be fixed.

2020-12-18 20:10 UTC, jvigliotta commented
@charlesh88 updated the css!

2021-01-08 23:24 UTC, charlesh88 commented
Reviewing again and will resolve conflicts in the branch.

2021-01-08 23:46 UTC, charlesh88 submitted a review, later dismissed
New and improved! LGTM.

2021-01-09 01:16 UTC, nikhilmandlik submitted a review, later dismissed
Small cleanup, else LGTM

2021-01-09 01:16 UTC, nikhilmandlik commented on app.js
> +options.port = options.port || options.p || 8081;
for testing?

2021-02-01 18:04 UTC, deeptailor commented on app.js
> +options.port = options.port || options.p || 8081;
thats @charlesh88 signature 😃

2021-02-01 18:05 UTC, deeptailor commented
Looks great! Just needs one change (change port back to 8080) and we can merge it

2021-02-03 17:58 UTC, jvigliotta commented on app.js
> +options.port = options.port || options.p || 8081;
I'll take care of this one

2021-02-03 18:00 UTC, jvigliotta commented
> Looks great! Just needs one change (change port back to 8080) and we can merge it

Should be good now!

2021-02-05 21:14 UTC, deeptailor approved these changes
lgtm

2021-02-05 21:15 UTC, deeptailor commented
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? N/A UI
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
Has associated issue been labelled unverified? (only applicable if this PR closes the issue) Yes

2021-02-18 17:55 UTC, merged