UI edits
nasa/openmct pull request #3652
Opened 2021-01-25 21:07 UTC by Abster101

2021-01-25 21:09 UTC, Abster101 commented
Wanted to show you the integration that I mentioned via Teams but I'm sure there's a better way to go about doing that.

2021-02-03 17:36 UTC, Abster101 commented
![Screen Shot 2021-02-03 at 11 07 21 AM](https://user-images.githubusercontent.com/7283548/106786311-0689b800-6614-11eb-80ba-59dabe408cba.jpeg)
<img width="1680" alt="Screen Shot 2021-02-03 at 11 06 13 AM" src="https://user-images.githubusercontent.com/7283548/106786323-08ec1200-6614-11eb-86f3-fd92ba8081d3.png">

2021-02-03 17:44 UTC, deeptailor requested changes
I left a comment regarding the issue with the forms and the unknown type

2021-02-03 17:44 UTC, deeptailor commented on src/plugins/apresTimeline/plugin.js
> +
We need an initialize function like in the activity type, which should have domainObject.configuration, which will include the stateName, startTime and endTime with initial values

2021-02-03 17:45 UTC, deeptailor commented on src/plugins/apresTimeline/plugin.js
> +
With the icon issue, its showing an unknown type in the second picture. Delete these via right click, and create a new chronicle, and see if that works

2021-03-16 22:01 UTC, closed without merging