[Feature Branch] Add Compass Rose and Compass HUD to Imagery View
nasa/openmct pull request #3659
Opened 2021-01-29 22:49 UTC by davetsay

## Overview
Addresses #3658 
merging into feature branch `imagery-enhancements`

## Testing Instructions 
see #3658 

## Author Checklist
| | |
| --- | :---: |
| Changes address original issue? | Y |
| Unit tests included and/or updated with changes? | N/A |
| Command line build passes? | Y |
| Changes have been smoke-tested? | Y |
| Testing instructions included? | Y |

2021-01-29 22:51 UTC, davetsay commented
@akhenry , @jvigliotta , @charlesh88 , this is only merging into feature branch but it should be easier to review this chunk independently.

2021-02-01 17:45 UTC, deeptailor requested changes
Looks great, just a couple of comments

2021-02-01 17:45 UTC, deeptailor commented on src/plugins/imagery/components/Compass/Compass.vue
> +            return this.image['Camera Tilt'];
Is there a reason why we are not using snake case for keys?

2021-02-01 17:45 UTC, deeptailor commented on src/plugins/imagery/components/ImageryViewLayout.vue
> +                && this.imageContainerHeight !== undefined;
We could add these variables into an array and do: VARIABLES.all(variable => variable !== undefined), so we are not repeating logic.

2021-02-04 21:43 UTC, merged