[Testing] Resolve all promises
nasa/openmct pull request #3829
Opened 2021-04-23 19:25 UTC by davetsay

## Overview
Closes #3828 

## Testing Instructions 
See #3828 

## Author Checklist
| | |
| --- | :---: |
| Changes address original issue? | Y |
| Unit tests included and/or updated with changes? | Um... yeah |
| Command line build passes? | Y |
| Changes have been smoke-tested? | Y |
| Testing instructions included? | Y |

2021-04-23 19:26 UTC, davetsay commented
Dunno if changing `resetApplicationState` to `resetApplicationStatePromise` is too weird. But, thats what reviews are for. There were quite a few resetApplicationStates that were not returned or awaited on.

2021-05-05 18:29 UTC, shefalijoshi submitted a review, later dismissed
LGTM

2021-05-12 17:13 UTC, akhenry requested changes
This looks great, it's a lot of work!

I am unsure about naming a function `resetApplicationStatePromise()`. I totally understand the motivation behind renaming it so that it's more obvious that it returns a promise. As a developer though I would expect something named `resetApplicationStatePromise` to be a promise object.

I *think* that just fixing the existing usage of this function will make the problem go away? People copy existing test specs to create new ones, so they will copy the correct usage.

Also, if we could fix that x-ed out test that would be awesome.

2021-05-12 17:13 UTC, akhenry commented on src/plugins/LADTable/pluginSpec.js
> +        xit("should show one row per lad table object in the composition", () => {
Any way we can fix this?

2021-05-26 04:32 UTC, davetsay commented on src/plugins/LADTable/pluginSpec.js
> +        xit("should show one row per lad table object in the composition", () => {
I didn't think so, no. But its fixed.

2021-05-26 04:33 UTC, davetsay commented
> This looks great, it's a lot of work!
> 
> I am unsure about naming a function `resetApplicationStatePromise()`. I totally understand the motivation behind renaming it so that it's more obvious that it returns a promise. As a developer though I would expect something named `resetApplicationStatePromise` to be a promise object.
> 
> I _think_ that just fixing the existing usage of this function will make the problem go away? People copy existing test specs to create new ones, so they will copy the correct usage.
> 
> Also, if we could fix that x-ed out test that would be awesome.

Okay. Reverted the naming.

2021-05-26 04:33 UTC, davetsay commented
@akhenry addressed your comments. Can you re-review?

2021-05-27 23:42 UTC, akhenry commented
@davetsay Merge conflict 😦

2021-05-28 00:00 UTC, nikhilmandlik commented
> @davetsay Merge conflict 😦

this could be my fault, back button fix also uses some of same changes.

2021-05-28 22:59 UTC, akhenry commented
@davetsay  @nikhilmandlik  Can we resolve?

2021-06-16 17:08 UTC, akhenry commented
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y++
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

2021-06-18 23:06 UTC, akhenry approved these changes

2021-06-18 23:06 UTC, merged