[Link Action] New style plugin
nasa/openmct pull request #3842
Opened 2021-04-27 22:17 UTC by jvigliotta

Removed old link action legacy code and added new link action style plugin.

closes #3835 

### Author Checklist
Check | Passed
-- | --
Changes address original issue? | Y
Unit tests included and/or updated with changes? | Y
Command line build passes? | Y
Changes have been smoke-tested? | Y
Testing instructions included? | Y

2021-05-03 19:20 UTC, shefalijoshi requested changes
Looks really good, suggesting some changes.

2021-05-03 19:20 UTC, shefalijoshi commented on src/plugins/linkAction/pluginSpec.js
> +    const LINK_ACITON_KEY = 'link';
Oh yeah!! `LINK_ACITON_KEY` :P

2021-05-03 19:20 UTC, shefalijoshi commented on src/plugins/linkAction/LinkAction.js
> +            let sameObjectOrChildAlready = parentCandidateKeystring === objectToLinkKeystring
Use `openmct.objects.areIdsEqual `here instead

2021-05-03 19:20 UTC, shefalijoshi commented on src/plugins/linkAction/LinkAction.js
> +            return this.openmct.composition.checkPolicy(
Can we get rid of this legacy code and use a new Composition policy instead?
See `ConditionSetCompositionPolicy`

2021-05-03 19:20 UTC, shefalijoshi commented on src/plugins/linkAction/LinkAction.js
> +        let compositionCollection = this.openmct.composition.get(newParent);
Hmm. Why not `newParent.composition.add(child)` ?

2021-08-06 18:29 UTC, jvigliotta commented
Closing this as it's addressed in #3816

2021-08-06 18:41 UTC, jvigliotta commented
handled in PR #3816

2021-08-06 18:41 UTC, closed without merging