Sync time conductor with plots time range
nasa/openmct pull request #3843
Opened 2021-04-27 23:41 UTC by shefalijoshi

When plots time range differs from the time conductor (zoom or pan), provide an action to the user to sync the time conductor's range with the plot.

2021-04-30 00:21 UTC, charlesh88 commented
I have made several changes and pushed to the branch:
- Reordered buttons and changed to use v-ifs instead of :disabled;
- Fixed Pause/Play to properly toggle a single button, rather than displaying two buttons;
- Pause/Play button now has consistent look as elsewhere;
- Pausing a plot with Pause/Play now displays the Sync button;
- Added new mixin `smallerControlButtons` which is now used by object frames in layouts and Timestrip swimlanes to shrink contained view control buttons in those contexts;

2021-04-30 00:22 UTC, charlesh88 requested changes
Pausing the plot via Pause/Play must display the orange warning border and icon as elsewhere.

2021-05-05 16:55 UTC, shefalijoshi commented
> Pausing the plot via Pause/Play must display the orange warning border and icon as elsewhere.

@charlesh88 This is fixed now.

2021-05-05 18:11 UTC, charlesh88 approved these changes
LGTM

2021-05-12 17:21 UTC, akhenry commented on src/plugins/plot/vue/single/MctPlot.vue
> +                this.setStatus(isUnsynced);
👍

2021-05-12 17:48 UTC, akhenry approved these changes
Looks good to me!

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

2021-05-12 17:57 UTC, merged