Allow browser-based context-click to download Imagery
nasa/openmct pull request #3857
Opened 2021-05-03 23:55 UTC by charlesh88

Simple fix to allow browser context-clicking to download imagery. Fixes #3756.
- `pointer-events: none` added to `c-compass` wrapper (which was blocking the image from catching mouse events), and `pointer-events: all` added to `c-direction-rose` element;
- Unit tested locally in main view and both types of layouts;
- Fixed indention spacing in file;

2021-05-05 18:23 UTC, shefalijoshi commented
@charlesh88 It looks like the previous and next buttons also prevent the context save menus for images:
![image](https://user-images.githubusercontent.com/5247066/117190502-5e12fd80-ad94-11eb-87b7-5d3d776e3b30.png)

2021-05-05 18:24 UTC, shefalijoshi requested changes
Compass fix looks good!
 
However, the previous and next buttons seem to prevent the image menu items as well.

2021-05-07 20:56 UTC, charlesh88 commented
> Compass fix looks good!
> 
> However, the previous and next buttons seem to prevent the image menu items as well.

@shefalijoshi Yes, any clickable controls are going to prevent the browser-based menu from displaying - this is normal and can't be solved with this approach. A more long term solution would be to add an explicit Save action, available in the view's 3 dot menu - but let's get this in first.

2021-05-17 21:22 UTC, charlesh88 commented
@shefalijoshi Conflicts resolved, this PR should be good to go.

2021-05-18 21:41 UTC, shefalijoshi commented
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y
6. Has associated issue been labelled `bug`? (only applicable if this issue is a bug) Y

2021-05-18 21:42 UTC, shefalijoshi approved these changes
Looks good!

2021-05-18 21:42 UTC, merged