Updates to the sprint cycle and end of sprint release process
nasa/openmct pull request #3878
Opened 2021-05-17 18:33 UTC by shefalijoshi

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N/A
3. Command line build passes? Y
4. Changes have been smoke-tested? N/A
5. Testing instructions included? N/A

2021-05-26 14:05 UTC, unlikelyzero submitted a review, later dismissed
### Reviewer Checklist
- [ ] Changes appear to address issue?
- [ ] Appropriate unit tests included?
- [ ] Code style and in-line documentation are appropriate?
- [ ] Commit messages meet standards?
- [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
- [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2021-05-27 00:36 UTC, akhenry requested changes
@shefalijoshi  @unlikelyzero  This looks fantastic, really great. 

I've provided some clarity about the criticality levels we've been using during triage in an inline comment.

2021-05-27 00:36 UTC, akhenry commented on CONTRIBUTING.md
>  * _Trivial_: Minimal impact on the usefulness and functionality of the
I'd like to align these definitions a little better with how we use them in our triage sessions:
* _Trivial_: Minimal impact on the usefulness and functionality of the software; a "nice-to-have." Visual impact without functional impact,
* _Medium_: Some impairment of use, but simple workarounds exist
* _Critical_: Significant loss of functionality or impairment of use. Display of telemetry data is not affected though.
* _Blocker_: Major functionality is impaired or lost, threatening mission success. Display of telemetry data is impaired or blocked by the bug, which could lead to loss of situational awareness.

2021-05-27 17:45 UTC, unlikelyzero approved these changes

2021-05-28 19:10 UTC, akhenry approved these changes
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - documentation changes only
3. Code style and in-line documentation are appropriate? N/A - documentation changes only
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)

2021-05-28 19:24 UTC, merged