Add resize event and disable pointer events on iframes on trigger of resize
nasa/openmct pull request #4016
Opened 2021-07-13 17:32 UTC by khalidadil

### Resolves

#3986

### Author Checklist

Check | Passed
-- | --
Changes address original issue? | Y
Unit tests included and/or updated with changes? | N/A
Command line build passes? | Y
Changes have been smoke-tested? | Y
Testing instructions included? | N/A

Testing instructions are included in #3986

2021-07-13 21:18 UTC, davetsay commented
@charlesh88 , the approach and the scss change looks good to me. Can you give @khalidadil your stylistic blessing?

2021-07-14 16:31 UTC, davetsay requested changes
This looks good. I have a couple of minor code style changes.

Can we change `openmct-start-drag` and `openmct-end-drag` to `start-resizing` and `end-resizing` to be consistent with the rest of the feature flow?

One comment inline about vue class bindings.

2021-07-14 16:31 UTC, davetsay commented on src/ui/layout/Layout.vue
> +        :class="['l-shell__main', isResizing ? 'l-shell__resizing' : '']"
This is fine and you'll see this a lot in our codebase. We should try to bind dynamic styling to computed class and style objects though so these don't get out of hand. Static classes can be left in their own non bound attribute

2021-07-14 17:11 UTC, unlikelyzero commented
@khalidadil there is current a failing test on master for `ci/circleci: node10-chrome` and I'm investigating now

2021-07-14 17:13 UTC, davetsay approved these changes
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | N/A |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |

2021-07-15 00:32 UTC, merged

2021-07-15 00:35 UTC, unlikelyzero commented
@khalidadil I updated your branch with the master test fixes and it's gone through