Snapshots local storage
nasa/openmct pull request #4020
Opened 2021-07-14 00:37 UTC by nikhilmandlik

### Resolves:
resolves: #4007

### All Submissions:
* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

2021-08-16 21:12 UTC, akhenry commented
@nikhilmandlik  Is this ready to review again?

2021-08-25 14:05 UTC, shefalijoshi requested changes
Looks great! Some changes requested.

2021-08-25 14:05 UTC, shefalijoshi commented on src/plugins/notebook/components/NotebookEmbed.vue
> +        isSnapshotContainer: {
Since you're providing the `snapshotContainer` to this view, won't `isSnapshotContainer` always be true? Or is that prop named incorrectly?

2021-08-25 14:05 UTC, shefalijoshi commented on src/plugins/notebook/components/Notebook.vue
> +                const namespace = this.domainObject.identifier.namespace;
See comment about using `identifierService` below.

2021-09-13 20:20 UTC, shefalijoshi commented on src/plugins/notebook/utils/notebook-image.js
> +    object.identifier.namespace = namespace;
OK

2021-09-13 20:44 UTC, shefalijoshi approved these changes
Nice work! Thank you

2021-09-13 20:44 UTC, merged