Mct4039
nasa/openmct pull request #4057
Opened 2021-07-27 01:04 UTC by scottbell

### All Submissions:

* [x ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x ] Changes address original issue?
* [x ] Unit tests included and/or updated with changes?
* [ x] Command line build passes?
* [x ] Has this been smoke tested?
* [ x] Testing instructions included in associated issue?

2021-07-27 01:06 UTC, scottbell commented on src/plugins/plot/stackedPlot/StackedPlot.vue
> +            const plotElement = this.$el;
plotContainer wasn't resolving, so switched to just $el. there's probably a more elegant way to do this

2021-07-27 01:06 UTC, scottbell commented on src/plugins/plot/stackedPlot/StackedPlot.vue
> +            const plotElement = this.$el;
same as above

2021-07-27 20:25 UTC, scottbell commented on src/plugins/plot/stackedPlot/StackedPlot.vue
> +            const plotElement = this.$el;
this was preventing StackedPlots from exporting images by the way. this seemed broken in master as well.

2021-07-29 19:02 UTC, akhenry requested changes
This looks great, thanks! 

My only suggestion would be that we might want to add a test that exercises the `renderElement` function. ie. create a dom element, invoke `renderElement` and pass in the element, then check that the promise that is returned resolves with a blob. I don't think we can really do much beyond checking that it returns a blob. Trying to glean anything meaningful from the blob itself is probably a waste of time.

2021-07-29 19:29 UTC, scottbell commented on src/exporters/ImageExporter.js
> +function polyfillToBlob() {
Polyfill is toast

2021-07-29 23:41 UTC, akhenry submitted a review, later dismissed

2021-07-30 05:01 UTC, akhenry approved these changes

2021-07-30 05:05 UTC, merged

2021-07-30 05:05 UTC, akhenry commented
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y