Fix plots performance
nasa/openmct pull request #4092
Opened 2021-08-06 21:04 UTC by shefalijoshi

Separates plots series telemetry data storage from it's configuration so that Vue reactivity does not creep into the data and adversely affect performance

Resolves #4084 

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

2021-08-10 15:20 UTC, davetsay requested changes
looks good. just some questions on some code that might have snuck in. if they are good changes, should be good to go in.

2021-08-10 15:20 UTC, davetsay commented on src/plugins/plot/MctPlot.vue
> -            this.setCursorGuideVisibility(newCursorGuide);
is this related to this pr?

2021-08-10 15:20 UTC, davetsay commented on src/plugins/plot/MctPlot.vue
> -
is this related to this pr?

2021-08-10 15:20 UTC, davetsay commented on src/ui/layout/BrowseBar.vue
>          window.addEventListener('beforeunload', this.promptUserbeforeNavigatingAway);
is this related to this pr?

2021-08-12 23:26 UTC, akhenry approved these changes
Looks good to me. From some basic profiling I did locally with SWGs it looks much more performant. Processor usage on a single SWG plot dropped from 70%-80% to 30%-40% which is awesome. Nice work!

2021-08-12 23:27 UTC, akhenry commented
@davetsay I'll leave it with you to follow up on your review comments and merge this.

2021-08-16 21:14 UTC, shefalijoshi commented on src/plugins/plot/configuration/configStore.js
> -        this.store[id].destroy();
Yeah. Not all config stores have it.

2021-08-16 21:20 UTC, davetsay approved these changes
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | Y |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |

2021-08-16 21:21 UTC, merged