Flexible inspector properties
nasa/openmct pull request #4109
Opened 2021-08-11 21:44 UTC by davetsay

Closes #3990 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes? pending non related lint fixes in #4082
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

2021-08-11 21:46 UTC, davetsay commented
@akhenry this is the change which allows us to customize the details block in inspector, and specifically custom details for MMGIS features.

Writing tests now but wanted you to verify this strategy first if possible

2021-08-13 20:50 UTC, akhenry requested changes
Looks good to me! Just two questions.

2021-08-16 21:29 UTC, davetsay commented on src/ui/inspector/Inspector.vue
> +                    v-if="!activity"
I don't know to be honest. I just bubbled this logic up from the properties component. I'll take another look.

2021-09-02 23:09 UTC, davetsay commented on src/ui/inspector/details/Properties.vue
> +        <Component
removed `detail-time`

2021-09-03 00:18 UTC, davetsay commented on src/ui/inspector/Inspector.vue
> +                    v-if="!activity"
Created #4180 to refactor plan activities to leverage this code so the hard coding can be removed. It looks like we can do so but need to check with someone familiar with plan design to make sure (@charlesh88 , @tiffanyatruong , @shefalijoshi).

2021-09-14 00:54 UTC, akhenry commented on src/ui/inspector/Inspector.vue
> +                    v-if="!activity"
Sounds good, I'm happy for this to be addressed in a followup if this is pre-existing logic.

2021-09-14 00:56 UTC, akhenry requested changes
Just needs some unit tests, otherwise it's good to go. You can mount and test the component in isolation, no need to test it in the context of the full app.

2021-09-17 04:12 UTC, davetsay commented
> Just needs some unit tests, otherwise it's good to go. You can mount and test the component in isolation, no need to test it in the context of the full app.

Added unit tests

2021-09-17 23:20 UTC, akhenry approved these changes
Looks great. Thanks!

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

2021-09-17 23:20 UTC, merged