Reimplementation import export json
nasa/openmct pull request #4171
Opened 2021-08-31 22:04 UTC by kobe1104

This PR is extracted from https://github.com/nasa/openmct/pull/3816

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

2021-09-01 00:40 UTC, kobe1104 commented
@nikhilmandlik I've removed all the forms changes and kept only the import export plugins. I also removed the old 'import-export' folder.

2021-09-01 18:12 UTC, nikhilmandlik commented on src/plugins/exportAsJSONAction/ExportAsJSONAction.js
> +    // Public
sorry I missed this one, can we add JsDoc

2021-09-01 18:13 UTC, nikhilmandlik commented on src/plugins/exportAsJSONAction/ExportAsJSONAction.js
> +    // Private
add JsDoc

2021-09-01 18:13 UTC, nikhilmandlik commented on src/plugins/importFromJSONAction/ImportFromJSONAction.js
> +    // Public
same add JsDoc

2021-09-01 18:13 UTC, nikhilmandlik commented on src/plugins/importFromJSONAction/ImportFromJSONAction.js
> +    // Private
add JsDoc

2021-09-01 22:49 UTC, kobe1104 commented
Hi @nikhilmandlik I've added the JSdoc to them. I added mostly the data types. Let me know if there's anything else.

2021-09-14 01:40 UTC, akhenry reviewed
This looks really great @kobe1104. It just needs some tests.

2021-09-14 01:40 UTC, akhenry commented on src/plugins/exportAsJSONAction/ExportAsJSONAction.js
> +import ExportService from '../../../platform/exporters/ExportService.js';
Awesome that we can just reuse the ExportService as is, but this needs to be moved under `src/`. The whole `platform/` directory is going to go away.

2021-09-14 01:40 UTC, akhenry commented on src/plugins/importFromJSONAction/ImportFromJSONAction.js
> +        this.openmct.forms.showForm(formStructure, {
@nikhilmandlik Remind me why all forms need a `domainObject` and a `parentDomainObject`? In fact, in this case it doesn't seem as though any domain objects should be needed?

2021-09-14 01:43 UTC, akhenry requested changes
sdfsdfdsfsdfsdfsdf

2021-09-14 03:28 UTC, nikhilmandlik commented
@akhenry just a test comment 😄

2021-09-17 21:30 UTC, kobe1104 commented
Hi @akhenry I've created a separated PR for the test: https://github.com/nasa/openmct/pull/4225

2021-10-19 18:48 UTC, kobe1104 commented
Hi @akhenry The new import/export JSON are moved under /src and I've removed the old import/export actions from platform. Also the comments of '// Private' have been removed.

2021-11-08 21:44 UTC, akhenry commented
@kobe1104 @nikhilmandlik to resolve merge conflicts.

2021-11-08 21:47 UTC, kobe1104 commented
@akhenry @nikhilmandlik I've fixed the conflict

2021-12-03 20:47 UTC, nikhilmandlik commented on src/exporters/JSONExporter.js
> +        let filename = (options && options.filename) || "test-export.json";
test-export.json?

2021-12-03 20:48 UTC, nikhilmandlik approved these changes
Small change else looks good

2021-12-03 21:34 UTC, merged