[Telemetry Collections] Add process method to historical request options (for yield requests)
nasa/openmct pull request #4201
Opened 2021-09-09 18:47 UTC by jvigliotta

This adds the processTelemetry method to the options that are sent to historical providers. No changes affect Open MCT or Telemetry Collections. It is up to the historical provider to do something with the method.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

2021-09-15 15:41 UTC, akhenry requested changes
Looks good to me, although proposed changes in https://github.com/akhenry/openmct-yamcs/pull/81/files will likely necessitate a minor change here as well.

2021-09-16 18:18 UTC, jvigliotta commented
@akhenry yep! had to make some changes to the name and now suppressing abort errors from console.

2021-09-18 00:45 UTC, akhenry approved these changes

2021-09-18 00:46 UTC, akhenry commented
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - small fix
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

2021-09-18 00:50 UTC, merged