New import export json test
nasa/openmct pull request #4225
Opened 2021-09-17 21:29 UTC by kobe1104

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

2021-12-06 22:51 UTC, nikhilmandlik commented
@kobe1104  some conflicts

2021-12-07 20:08 UTC, nikhilmandlik commented on src/plugins/exportAsJSONAction/ExportAsJSONAction.js
> +<<<<<<< HEAD
merge issue?

2021-12-23 19:39 UTC, davetsay requested changes
Half of the tests are arrow functions and half are regular ole functions. Can we pick one for all?

A comment, not a request. I'm not sure I understand what the difference between these tests are, `ExportAsJSONAction exports object from tree`, `can export self-containing objects`.

Some inline comments. Looking good.

2021-12-23 19:47 UTC, nikhilmandlik commented on src/plugins/exportAsJSONAction/ExportAsJSONActionSpec.js
> +import ExportAsJSONActionPlugin from './plugin';
good catch

2021-12-24 00:54 UTC, nikhilmandlik commented
> Half of the tests are arrow functions and half are regular ole functions. Can we pick one for all?
> 
> A comment, not a request. I'm not sure I understand what the difference between these tests are, `ExportAsJSONAction exports object from tree`, `can export self-containing objects`.
> 
> Some inline comments. Looking good.

yeah updated, `can export self-containing objects` has infinite Parent and child relation, parent contains child and child contains parent. 
eg:
<img width="274" alt="Screen Shot 2021-12-23 at 4 54 05 PM" src="https://user-images.githubusercontent.com/1292612/147303049-c0135d69-f0a5-4162-9714-0d212e82baf2.png">

2021-12-27 20:29 UTC, davetsay approved these changes
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | Y |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |

2021-12-27 20:29 UTC, merged