Add Condition widget test
nasa/openmct pull request #4292
Opened 2021-10-06 13:24 UTC by scottbell

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? Will users need to change how they are calling the API, or how they've extended core plugins such as Tables or Plots?

### Author Checklist

* [X] Changes address original issue?
* [X] Unit tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [X] Testing instructions included in associated issue?

2021-10-13 23:36 UTC, nikhilmandlik commented on src/utils/testing.js
> +            conditionWidget: {
wondering if this is correct place to add mock data (unless used by multiple plugins/components).
In this case I think mock data is specific to `conditionWidget`, I guess we can define it in conditionWidget spec file?

2021-10-13 23:36 UTC, nikhilmandlik requested changes
Looks good just one small change / suggestion.

2021-10-18 19:56 UTC, akhenry commented
Something kinda wild going on with this PR - 88 files changed.Is this based on the 1.7.8 branch? Might need to be rebased over master.

2021-10-18 20:30 UTC, scottbell commented
> Something kinda wild going on with this PR - 88 files changed.Is this based on the 1.7.8 branch? Might need to be rebased over master.

Yes, before changing the branch target, it had a lot fewer changed files!

2021-10-26 08:27 UTC, closed without merging