[Timer] Re-implement Timer object in Vue.js
nasa/openmct pull request #4311
Opened 2021-10-13 18:49 UTC by khalidadil

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? Will users need to change how they are calling the API, or how they've extended core plugins such as Tables or Plots?

### Author Checklist

* [X] Changes address original issue?
* [X] Unit tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [X] Testing instructions included in associated issue?

2021-10-13 18:50 UTC, khalidadil commented on src/api/objects/ObjectAPI.js
> +/**
Change made by Andrew and merged into this branch

2021-10-13 18:51 UTC, khalidadil commented on src/api/objects/object-utils.js
> +        let deleted = _.difference(Object.keys(oldObject), Object.keys(newObject));
Change made by Andrew and merged into this branch

2021-10-13 23:41 UTC, nikhilmandlik commented on src/plugins/timer/actions/PauseTimerAction.js
> + * Open MCT, Copyright (c) 2009-2021, United States Government
I think we might want to move this from /platform to /src folder?

2021-10-14 18:37 UTC, nikhilmandlik commented on src/plugins/timer/actions/PauseTimerAction.js
> + * Open MCT, Copyright (c) 2009-2021, United States Government
ahh ok cool

2021-11-01 19:53 UTC, khalidadil commented on src/plugins/timer/components/Timer.vue
> +            } else if (this.configuration && this.configuration.timestamp === undefined) {
yes, since I do want to set the `relativeTimestamp` to `undefined` if the configuration `timestamp` is `undefined` without running it through moment.

2021-11-03 16:38 UTC, khalidadil commented
@nikhilmandlik @davetsay I think this is pretty good now coverage-wise? What do y'all think?

2021-11-08 22:01 UTC, davetsay requested changes
super small change to not have both required and default on a vue prop. Maybe run the test and lint checks again. I feel like the lint checker should have caught that.

2021-11-09 18:22 UTC, davetsay approved these changes
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | Y |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |

2021-11-09 22:41 UTC, merged