4390 - [UTCTimeFormat] Convert to ES6 Plugin
nasa/openmct pull request #4412
Opened 2021-10-30 16:33 UTC by mariuszr

Addresses #4390 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

2021-10-30 17:22 UTC, unlikelyzero commented
@mariuszr for some reason, this PR is not being picked up by our codecoverage bot. I've issued a rebase to see if it triggers the change. I've created https://github.com/nasa/openmct/issues/4413 to investigate further. Sorry for the inconvenience!

2021-11-26 23:29 UTC, jvigliotta commented
@mariuszr  this looks great! can you add test similar to: https://github.com/nasa/openmct/blob/master/src/plugins/ISOTimeFormat/pluginSpec.js then this should be good to go

2021-11-26 23:33 UTC, mariuszr commented
> @mariuszr this looks great! can you add test similar to: https://github.com/nasa/openmct/blob/master/src/plugins/ISOTimeFormat/pluginSpec.js then this should be good to go. If not, we can always create an issue for a test. Let me know.

2021-11-26 23:36 UTC, mariuszr commented
Reopen as accidentally I  closed it :)

2021-11-27 16:13 UTC, mariuszr commented
Hi @jvigliotta, I have added a test for the plugin. Please check it and let me know

2021-12-06 19:37 UTC, jvigliotta requested changes
One _small_ little change, then looks good to go. Thank you for this! I like the optional format checks in the tests as well, nice work!

2021-12-06 19:37 UTC, jvigliotta commented on src/plugins/UTCTimeFormat/pluginSpec.js
> +    const ISO_KEY = 'utc';
Can we change this to UTC_KEY?

2021-12-06 19:48 UTC, mariuszr commented on src/plugins/UTCTimeFormat/pluginSpec.js
> +    const ISO_KEY = 'utc';
Oh, my bad. Corrected.

2021-12-06 20:28 UTC, jvigliotta approved these changes
Looks great, thanks @mariuszr !

### Reviewer Checklist
Check | Passed
-- | --
Changes appear to address issue?? | Y
Appropriate unit tests included? | Y
Code style and in-line documentation are appropriate? | Y
Commit messages meet standards? | Y
Has associated issue been labelled unverified? (if PR closes issue) | Y

2021-12-06 20:29 UTC, merged