Make legacy support optional
nasa/openmct pull request #4614
Opened 2021-12-18 21:55 UTC by akhenry

This PR renders support for Open MCT's legacy API optional by moving the entire adapter layer into a plugin. 

Support for the legacy API will be completely removed in a future release because it depends upon Angular 1.x which is now at EOL.

Legacy support can be enabled by installing the new legacy support plugin like so:

```
openmct.install(openmct.plugins.LocalStorage());
```

For now it remains installed by default in the Open MCT source. [A followup issue](https://github.com/nasa/openmct/issues/4613) has been filed to ensure that legacy support is disabled by default in 1.8.3.

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [X] Changes address original issue?
* [X] Unit tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

2021-12-20 22:11 UTC, unlikelyzero commented
Note: This is passing our smoke tests.

2021-12-26 22:00 UTC, davetsay requested changes
This is great @akhenry . I ran this in VISTA and there were no issues.

There are a couple of minor change requests inline.

2022-01-03 18:57 UTC, akhenry commented on src/plugins/legacySupport/plugin.js
> +export default function CouchPlugin(options) {
Hehehe, it suuuuuure is. Thanks!

2022-01-03 18:58 UTC, akhenry commented on src/plugins/plugins.js
> +    plugins.LegacyIndicators = LegacyIndicatorsPlugin.default;
Ok, lemme take a look. Thanks

2022-01-03 22:07 UTC, akhenry commented on src/plugins/plugins.js
> +    plugins.LegacyIndicators = LegacyIndicatorsPlugin.default;
Good catch, fixed and smoke tested with `example/notifications`

2022-01-03 22:07 UTC, akhenry commented on src/plugins/legacySupport/plugin.js
> +export default function CouchPlugin(options) {
Fixed

2022-01-03 22:20 UTC, davetsay approved these changes
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | Y |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |

2022-01-03 22:21 UTC, merged