Task automation and test improvement
nasa/openmct pull request #4673
Opened 2022-01-05 15:30 UTC by unlikelyzero

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

2022-01-10 23:21 UTC, akhenry requested changes
This looks really awesome, and adds a **lot** of value. Two small suggestions inline. I also want to make sure @jvigliotta takes a look at this.

2022-01-10 23:21 UTC, akhenry commented on .github/PULL_REQUEST_TEMPLATE.md
> +* [ ] List of Acceptance Tests Performed. These will be turned into e2e tests.
Could we remove this for now just to get the automation stuff in? The specifics of per-PR testing are currently under review.

2022-01-10 23:21 UTC, akhenry commented on .github/PULL_REQUEST_TEMPLATE.md
> +Closes: <!--- Insert Issue Number(s) this PR addresses. Typing # will open a dropdown of recent issues. -->
I'm not sure if the GitHub parser likes the colon here. I recently [merged a PR with `"resolves: #...."`](https://github.com/nasa/openmct/pull/4475) and it didn't automatically close the linked issue as expected, even though "resolves" is one of [GitHub's supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) . I had to close it manually. I've never had this issue without the colon (unless something else was wrong, like a typo in the keyword).

2022-01-11 00:06 UTC, jvigliotta commented
@unlikelyzero Maybe not a check-box, but can we mention something to the effect of "Any outside contributors must have a signed CLA on file."?

2022-01-19 23:56 UTC, unlikelyzero commented
@jvigliotta spun that out to automation here https://github.com/nasa/openmct/issues/4739

2022-01-20 14:02 UTC, shefalijoshi approved these changes
LGTM
### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled `bug`? (only applicable if this PR is for a bug fix)
* [ ] List of Acceptance Tests Performed.

2022-01-20 18:27 UTC, akhenry approved these changes

2022-01-20 18:31 UTC, merged