[MCT Tree] Enhance to be used as selection tree as well
nasa/openmct pull request #4734
Opened 2022-01-19 19:34 UTC by jvigliotta

The selection tree in forms and the main tree were previously two different, but very similar codebases. This PR merges the functionality of both into one codebase to prevent unnecessary duplication and more consistent functionality between the two.

Added the ability to make the main tree a selection tree with a passed in prop. If so, it will return the  selected tree item instead of navigating to it in the main view.

Updated Condition Widget style selector as well to use the new FormsAPI, which now has the new merged functionality tree in it by default.

closes: #4466 

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

2022-01-19 23:49 UTC, nikhilmandlik approved these changes
LGTM

2022-01-20 14:38 UTC, shefalijoshi requested changes
One small change. Will review again once that's done.

2022-01-20 14:38 UTC, shefalijoshi commented on src/plugins/condition/components/inspector/StylesView.vue
> +            const conditionWidgetParent = this.openmct.router.path[1];
Please rename this const to `conditionSetParent` since this is not related to condition widgets

2022-01-21 02:44 UTC, shefalijoshi approved these changes
### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled `bug`? (only applicable if this PR is for a bug fix)
* [ ] List of Acceptance Tests Performed.

2022-01-21 02:46 UTC, merged