Fix notebook sync
nasa/openmct pull request #4738
Opened 2022-01-19 23:12 UTC by akhenry

Fixes https://github.com/nasa/openmct/issues/4737

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [X] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

2022-01-20 14:00 UTC, shefalijoshi requested changes
Nice investigating!
One change to put objectAPI.refresh back.

2022-01-20 15:19 UTC, akhenry commented on src/api/objects/ObjectAPI.js
> -/**
I'm not actually removing it, the function is duplicated [here](https://github.com/nasa/openmct/blob/master/src/api/objects/ObjectAPI.js#L473) and [here](https://github.com/nasa/openmct/blob/master/src/api/objects/ObjectAPI.js#L525). I'm just removing one of the copies.

2022-01-20 19:24 UTC, shefalijoshi commented
@akhenry Please resolve confict so I can merge this. Thanks!

2022-01-21 02:41 UTC, shefalijoshi approved these changes

2022-01-21 02:42 UTC, shefalijoshi commented
### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled `bug`? (only applicable if this PR is for a bug fix)
* [ ] List of Acceptance Tests Performed.

2022-01-21 02:43 UTC, merged