Imagery layers
nasa/openmct pull request #4968
Opened 2022-03-22 19:48 UTC by nikhilmandlik

Closes https://babelfish.arc.nasa.gov/jira/browse/NIRVSSOMCT-271
### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-03-23 18:11 UTC, charlesh88 commented
- I've added testing notes for the layers functionality specifically in 271 in the NIRVSSOMCT repo.

2022-04-01 19:33 UTC, shefalijoshi commented
@nikhilmandlik There was another change by @michaelrogers that refactored the filters into a different component. Was that PR merged? If not, it should be merged first.

2022-04-01 20:10 UTC, michaelrogers commented
> @nikhilmandlik There was another change by @michaelrogers that refactored the filters into a different component. Was that PR merged? If not, it should be merged first.

It was indeed merged here: https://github.com/nasa/openmct/pull/4736

That PR added the ImageControls.vue component.

2022-04-05 16:52 UTC, nikhilmandlik commented
> Please consolidate the Filter settings refactor and re-request review.

Yup, its based of those changes from (@michaelrogers ) and your (@shefalijoshi) changes from image layer pr 😃

2022-04-06 00:12 UTC, charlesh88 approved these changes
This is awesome, looks great.

2022-04-06 21:13 UTC, shefalijoshi requested changes

2022-04-06 21:15 UTC, shefalijoshi commented
Notebook snapshot fails with this error:
![image](https://user-images.githubusercontent.com/5247066/162072215-5247525e-3f3e-4430-bb1a-c3aa0b421540.png)

2022-04-07 20:39 UTC, nikhilmandlik commented on src/plugins/imagery/components/ImageControls.vue
> +            this.notifyFiltersChanged();
also used in `handleResetFilters` so better to keep it as it is.

2022-04-18 20:44 UTC, shefalijoshi requested changes
@nikhilmandlik Still seeing the CORS issue for snapshots

2022-04-18 20:59 UTC, nikhilmandlik commented
> @nikhilmandlik Still seeing the CORS issue for snapshots

Yes thats expected and browser prevents snapshotting/capture of page from different domain.

2022-05-20 04:39 UTC, shefalijoshi reviewed
Please resolve conflicts. Looks good otherwise.

2022-05-23 20:38 UTC, shefalijoshi approved these changes

2022-06-04 01:24 UTC, merged