Use navigator platform to display separate for Linux OS - 4848
nasa/openmct pull request #5115
Opened 2022-04-26 14:17 UTC by michaelrogers

Closes #4848 and #5023

### Describe your changes:

- [x] Describe different alt text based on platform
- [x] Update tests to differentiate the help text based on platform.
- [x] Also adds some timing consistency to address #5023 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-04-28 23:10 UTC, unlikelyzero approved these changes
This is amazing. We should sync on modifying the test to only run in specific ways on specific 'projects'

2022-04-29 21:57 UTC, unlikelyzero requested changes
Let's try to evaluate this at the test framework level

2022-04-29 21:57 UTC, unlikelyzero commented on e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
> +    test('Image Pan/Zoom alt text is displayed (Linux)', async ({ page }) => {
test.skip(process.platform != 'darwin', 'Image Plan / Zoom alt text is displayed (Linux)', async ({ page, browserName })

2022-05-02 18:01 UTC, shefalijoshi approved these changes
Looks good to me!

2022-05-02 21:57 UTC, michaelrogers commented on e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
> +        const panHotkey = process.platform === 'linux' ? ['Control', 'Alt'] : ['Alt'];
@johnhill2 - Disappointingly Playwright failed to parse a modifier sequence like `Control+Alt` so the test had to be modified to map over an array of key presses.

2022-05-03 15:24 UTC, unlikelyzero approved these changes

2022-05-03 15:24 UTC, unlikelyzero commented on e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
> +    // test('Image Pan/Zoom alt text is displayed (Linux)', async ({ page }) => {
@michaelrogers do you mind deleting these?

2022-05-03 17:18 UTC, merged