Add CouchDB Status Indicator
nasa/openmct pull request #5276
Opened 2022-06-01 17:25 UTC by ozyx

Closes #4888 

### Describe your changes:

Adds a status indicator to the CouchDB plugin which informs whether the connection is active, inactive, or pending (attempting to reconnect).

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-06-02 11:45 UTC, scottbell requested changes
Good work! I've got a few changes requests below if you please

2022-06-02 11:45 UTC, scottbell commented on src/plugins/persistence/couch/CouchChangesFeed.js
> +        }
We should have a default case here - and maybe throw an error if we get something strange?

2022-06-02 11:48 UTC, scottbell requested changes

2022-06-02 11:48 UTC, scottbell commented on src/plugins/persistence/couch/CouchObjectProvider.js
> +    _messageToIndicatorState(message) {
we should make this a private method with `#`

2022-06-02 11:48 UTC, scottbell commented on src/plugins/persistence/couch/CouchObjectProvider.js
> +        }
we should have a default case here

2022-06-02 11:48 UTC, scottbell commented on src/plugins/persistence/couch/CouchObjectProvider.js
> +            this.indicator.setIndicatorToState(DISCONNECTED);
We should probably log the error here too

2022-06-03 20:32 UTC, ozyx commented
@scottbell I was able to add some tests to check the status changes triggered by successful / failed `request` calls within `CouchObjectProvider`, but I was not able to figure out how to test status changes triggered by `SharedWorker` event messages. 

For example, the `PENDING` status is only triggered if there is an active `SharedWorker` listening to the changes feed, an event fires, and the `EventSource` reports its `readyState` as 'connecting'. I'm not sure how best to simulate this.

2022-06-06 11:17 UTC, scottbell commented on src/plugins/persistence/couch/CouchObjectProvider.js
> +        }
agreed, though i think we'll need to work that through the team

2022-06-06 11:34 UTC, scottbell commented
> @scottbell I was able to add some tests to check the status changes triggered by successful / failed `request` calls within `CouchObjectProvider`, but I was not able to figure out how to test status changes triggered by `SharedWorker` event messages.
> 
> For example, the `PENDING` status is only triggered if there is an active `SharedWorker` listening to the changes feed, an event fires, and the `EventSource` reports its `readyState` as 'connecting'. I'm not sure how best to simulate this.

Agree, in that case it's going to be pretty hard to simulate a full round trip. Maybe we should short circuit the worker/event sourcen logic in that case. We could just ensure `PENDING` is accepted by the indicator by manual calling `onSharedWorkerMessage` in the provider with a fake `state` message. What do you think?

2022-06-06 16:46 UTC, scottbell commented
Fantastic work!

2022-06-06 16:49 UTC, merged