Backmerge e2e code coverage changes and fixes into release/2.0.5
nasa/openmct pull request #5431
Opened 2022-07-05 15:12 UTC by unlikelyzero

### Describe your changes:
Backmerge and cherrypick of https://github.com/nasa/openmct/pull/5328

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-07-05 15:36 UTC, ozyx approved these changes
~~LGTM~~

2022-07-05 15:44 UTC, ozyx requested changes
Overall looks good but looks like an imagery test is failing due to undefined reference `bgImageLocator`.

Need to finish refactor:
https://github.com/nasa/openmct/pull/5431/files#diff-140ee0482ef8a20f5921a5a5c5e9408251fc6bb919bfbb0eb2126de6e25df30cR309

2022-07-05 15:51 UTC, scottbell commented
@unlikelyzero it looks like there are 29 files for this PR:
https://github.com/nasa/openmct/pull/5328/files
and 30 in the previous PR:
https://github.com/nasa/openmct/pull/5328/files
are we missing anything important?

2022-07-05 16:49 UTC, unlikelyzero commented
> @unlikelyzero it looks like there are 29 files for this PR: https://github.com/nasa/openmct/pull/5328/files and 30 in the previous PR: https://github.com/nasa/openmct/pull/5328/files are we missing anything important?

<img width="526" alt="Screen Shot 2022-07-05 at 9 48 07 AM" src="https://user-images.githubusercontent.com/12446869/177377369-ab654979-f6b0-4dad-b389-68b01f8949dc.png">

This change was already made on release/2.0.5. I _shouldn't_ have made it on master to keep our commit history clean

2022-07-05 23:59 UTC, ozyx commented on e2e/tests/plugins/imagery/exampleImagery.e2e.spec.js
> +            message: "verify that old images are discarded",
Good catch

2022-07-06 00:00 UTC, ozyx approved these changes

2022-07-06 00:00 UTC, ozyx commented
Need to resolve conflict in `package.json` but otherwise looks good to go

2022-07-06 00:12 UTC, merged

2022-07-06 16:56 UTC, akhenry commented
@unlikelyzero Does this close https://github.com/nasa/openmct/issues/5329 ?

2022-07-06 17:10 UTC, unlikelyzero commented
@akhenry almost. There are still failing tests merged onto 2.0.5 that weren't merged onto master. Also, some were lost because we didn't lock master and folks accidentally merged to the wrong branch. https://github.com/nasa/openmct/issues/5326#issuecomment-1175763627