[Remote Clock] Wait for first tick and recalculate historical request bounds
nasa/openmct pull request #5433
Opened 2022-07-05 20:51 UTC by ozyx

Closes #5221 

### Describe your changes:

Adds a `TelemetryRequestInterceptor`. Block historical requests until the remote clock receives its first tick, and then use the interceptor to recalculate the request bounds.

Tests to be added in a future PR.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-07-06 01:09 UTC, akhenry commented on src/api/telemetry/TelemetryAPI.js
> +/**
Nice one!

2022-07-06 01:10 UTC, akhenry commented on src/plugins/remoteClock/requestInterceptor.js
> +function requestInterceptor(openmct, remoteClockIdentifier, waitForBounds) {
Let's name what type of request interceptor it is. It's a `remoteClockRequestInterceptor`. Or something similar.

2022-07-06 01:41 UTC, ozyx commented on src/api/telemetry/TelemetryAPI.js
> +    async applyRequestInterceptors(identifier, request) {
This is also used by `TelemetryCollection` so it shouldn't be marked as private

2022-07-07 16:15 UTC, unlikelyzero commented on e2e/tests/plugins/telemetryTable/telemetryTable.e2e.spec.js
> +        // Verify that it is <= our new end bound
I would update the testcase name to include these additional checks

2022-07-07 18:30 UTC, akhenry requested changes

2022-07-07 18:30 UTC, akhenry commented on src/api/telemetry/TelemetryAPI.js
> +        return provider.request(domainObject, args)
The issue here is that the _provider_ is no longer receiving all of the arguments passed into the `request` function. Previously it was.

2022-07-07 19:42 UTC, unlikelyzero approved these changes
e2e improvements look great!

If you have time before Andrew's review, you might want to put in a Remote Clock stub that captures this behavior as filed in the initial bug.

```js
// /e2e/tests/plugins/remoteClock
//boilerplate
test.describe('Remote Clock Tests', () => {
    test.fixme('Remote Clock accepts telemetry on initial load', async ({ page }) => {
    //addInitScript to with remote clock
    //Navigate directly to telemetry by URL OR by clicking time conductor
    };
}

2022-07-07 23:48 UTC, akhenry approved these changes

2022-07-07 23:51 UTC, merged