Add TBD Readme
nasa/openmct pull request #5514
Opened 2022-07-15 17:44 UTC by unlikelyzero

Closes 

### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-07-15 18:10 UTC, jvigliotta commented on e2e/README.md
> +- were expensive to run due to the need to instantiate a real browser
if you're flowing in from "meant:" I'd recommend adding "e2e tests were expensive" in the beginning here.

2022-07-15 18:10 UTC, jvigliotta commented on e2e/README.md
> +- were flaky due to network conditions or the underlying protocols associated with testing a browser.
same as above, recommend adding "e2e tests were flaky" at the beginning.

2022-07-15 18:12 UTC, akhenry requested changes

2022-07-15 18:12 UTC, akhenry commented on e2e/README.md
> +However, as the web ecosystem has matured to the point where Mission Critical UIs are written for the Web (Open MCT), the e2e testing tools improved along with them. There are now fewer "trade-offs"
Typo, "choosing"

2022-07-15 18:12 UTC, akhenry commented on e2e/README.md
> +- enable browsers and web applications to reach 'mocked' states to cover deeper codepaths without mocking the browser, itself
No need for a comma here.

2022-07-15 18:12 UTC, akhenry commented on e2e/README.md
> +- Against a local development version of openmct
Open MCT is two words

2022-07-15 18:12 UTC, jvigliotta commented on e2e/README.md
> +However, as the web ecosystem has matured to the point where Mission Critical UIs are written for the Web (Open MCT), the e2e testing tools improved along with them. There are now fewer "trade-offs"
I'd say, ", the e2e testing tools have matured as well."

2022-07-15 18:13 UTC, jvigliotta commented on e2e/README.md
> +However, as the web ecosystem has matured to the point where Mission Critical UIs are written for the Web (Open MCT), the e2e testing tools improved along with them. There are now fewer "trade-offs"
Chosing -> Choosing

2022-07-16 19:21 UTC, ozyx approved these changes

2022-07-16 19:21 UTC, merged