Fix plot resize handling
nasa/openmct pull request #5637
Opened 2022-08-09 15:50 UTC by shefalijoshi

Closes #3036 #5395 [VIPEROMCT-116](https://trunk.arc.nasa.gov/jira/browse/VIPEROMCT-116)

### Describe your changes:
Don't request data if mouse click has no action
Don't request data if resize width is too small.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-08-09 16:13 UTC, unlikelyzero requested changes
Let's add a regression test for this since it's re-regressed at least three times since I started

2022-08-18 23:30 UTC, akhenry requested changes
Looks good, I think this is going to fix this issue once and for all :) Thanks for taking a look at it.

A couple of comments inline.

2022-08-19 15:50 UTC, shefalijoshi commented on src/plugins/plot/MctPlot.vue
> +const OFFSET_THRESHOLD = 50;
Chrome sends out 2 resize events sometimes and when we switch tabs there is a very small jump in size and then it goes back. So the threshold tries to alleviate unnecessary resizing.

2022-08-19 15:53 UTC, shefalijoshi commented on src/plugins/plot/MctPlot.vue
>              this.clear();
Yes, that's correct.

2022-08-19 16:30 UTC, shefalijoshi commented on src/plugins/plot/MctPlot.vue
> +        play(skipReloadOnInteraction) {
I agree. I've refactored the code, removing the need for the interaction flag. 
Also renamed some methods to clarify intention.

2022-08-19 22:27 UTC, akhenry commented on src/plugins/plot/MctPlot.vue
> +const OFFSET_THRESHOLD = 50;
I guess I'm curious whether a smaller number might work here. Or whether we should be debouncing something that we're not right now to remove noise?

2022-08-19 22:30 UTC, akhenry commented on src/plugins/plot/MctPlot.vue
> +        play(skipReloadOnInteraction) {
Changes look great, thank you!

2022-08-19 22:30 UTC, akhenry commented
@shefalijoshi Changes look really awesome, it's much cleaner now. Just wondering whether we can get away with a smaller threshold number than 50. Did it not work with smaller numbers than that?

2022-08-22 17:27 UTC, shefalijoshi commented on src/plugins/plot/MctPlot.vue
> +const OFFSET_THRESHOLD = 50;
The call is already debounced - I didn't see any improvements to make there.
As for the number - We could go with a lower number, but I saw 2 resize calls - One for a 7 px resize and one for 30something, so I went with 50.

2022-09-07 22:04 UTC, akhenry requested changes
Just one debugging statement left in there, otherwise looks great!

2022-09-07 22:04 UTC, akhenry commented on src/plugins/plot/MctPlot.vue
> +                console.log('inside');
Debugging code, let's remove.

2022-09-13 01:35 UTC, ozyx commented
This will need to be cherry picked onto 2.1.0 before merging, looks like some changes from master are tagging along.

2022-09-13 17:42 UTC, ozyx commented
> This will need to be cherry picked onto 2.1.0 before merging, looks like some changes from master are tagging along.

Done

2022-09-13 17:55 UTC, akhenry commented
@shefalijoshi Linting error :( Looks like `expect` is imported but never used in the e2e test.

2022-09-13 17:59 UTC, akhenry approved these changes

2022-09-13 18:02 UTC, unlikelyzero requested changes
Still needs a real test

2022-09-16 13:56 UTC, unlikelyzero requested changes
It looks like this PR was affected when we retargeted master and picked up the 54 commits.

Can you add the e2e test stubs back? They should still be valid.

Let's sync this afternoon to figure out why codecov annotations are saying that the changes aren't covered by tests.

2022-09-16 15:40 UTC, shefalijoshi commented
> 

I don't think the test stubs are needed anymore. We've covered clicking and resize tests as unit tests.

2022-09-19 17:35 UTC, akhenry commented
Suspect this will fix https://github.com/nasa/openmct/issues/4206 as well

2022-09-30 15:16 UTC, unlikelyzero approved these changes

2022-09-30 20:04 UTC, merged