Sort tree items locally on rename
nasa/openmct pull request #5643
Opened 2022-08-10 18:27 UTC by ozyx

Closes #5489 #5533 #5398

### Describe your changes:

Reorders the tree items locally on object rename. Previously, the tree was re-retrieving object compositions even though they had not changed, which caused stale objects to repopulate-- most noticeably while using CouchDB.

Also implements `aria-role: tree` for the mct-tree, and updates/adds some e2e `appActions` to make interacting with the tree a bit easier.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-08-10 19:11 UTC, unlikelyzero commented
While you're in there, can you add a component visual test for the tree in these various forms?

2022-08-10 19:59 UTC, ozyx commented
> While you're in there, can you add a component visual test for the tree in these various forms?
> 
> How does the other internal tree behave inside of a crate or edit modal?

Yes! Let me give that a shot.

Good question re: the tree within create/edit modals. The appActions I've added are only intended for use with the main tree. The same tree component is used throughout, so the accessibility role is still applied to those other trees. The action is the same, so maybe we can extract the common actions to a private method and expose two different appActions, one for the main tree, and the other for modal trees?

2022-08-10 20:21 UTC, unlikelyzero commented
> The action is the same, so maybe we can extract the common actions to a private method and expose two different appActions, one for the main tree, and the other for modal trees?

I would just make a test for the modal tree within this file and keep associated functions private to this file until we find a need to use them. Ideally, none of the tests outside of this suite would need be "interested" in that appAction, i would think

2022-08-10 20:46 UTC, ozyx commented
> I would just make a test for the modal tree within this file and keep associated functions private to this file until we find a need to use them. Ideally, none of the tests outside of this suite would need be "interested" in that appAction, i would think

Good call, agree we should avoid overpopulating the appActions

2022-08-16 19:32 UTC, scottbell commented on e2e/appActions.js
> +        return window.location.href.split('?')[0].match(regexp).at(-1);
should we use a [regular URL object](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams) here instead?

2022-08-16 19:41 UTC, scottbell requested changes
Minor changes

2022-08-16 19:41 UTC, scottbell commented on src/ui/layout/mct-tree.vue
> +            const temp = directDescendants.slice();
can we use a better variable name please? 😀

2022-08-17 16:14 UTC, scottbell commented on e2e/appActions.js
> +        return window.location.href.split('?')[0].match(regexp).at(-1);
We should not! The query parameters in the OpenMCT URLs are not really query parameters, even though they look like them.

2022-08-17 16:14 UTC, scottbell commented on e2e/appActions.js
> +        return window.location.href.split('?')[0].match(regexp).at(-1);
As they're all put after the `#`

2022-08-17 16:15 UTC, scottbell approved these changes
Strong work!

2022-08-17 16:16 UTC, merged