Misc UI fixes for release 2.0.8
nasa/openmct pull request #5684
Opened 2022-08-19 21:28 UTC by charlesh88

Closes #5640
Closes #5303 

### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-08-22 14:05 UTC, cr4yfish requested changes
Glanced over it and looks good. 
But I think you forgot to take out a console log. Tagged it.

2022-08-23 19:29 UTC, charlesh88 commented on src/plugins/displayLayout/plugin.js
> +            console.log(type, definition);
Thanks!

2022-08-23 19:52 UTC, michaelrogers approved these changes
These changes look good to me.

2022-08-23 22:09 UTC, akhenry commented on src/plugins/displayLayout/plugin.js
> +            console.log(type, definition);
@cr4yfish Thanks for your help reviewing this!

2022-08-23 22:11 UTC, akhenry requested changes
Looks like there are changes from Master in here. Blocking until we can clean it up.

2022-08-24 18:15 UTC, ozyx commented
Retargeted against master. This branch will need to be cherry-picked to get into a good state.

2022-08-24 18:33 UTC, charlesh88 commented
I will redo this against release/2.0.8.

2022-09-14 22:14 UTC, closed without merging