[Time Conductor] History not working correctly
nasa/openmct pull request #5687
Opened 2022-08-22 17:46 UTC by jvigliotta

Closes #5626

### Describe your changes:

Turns out, this was just being caused by a check for fixed vs realtime only happening once on load, moved the computed value to a method (should be safe as this is only updated when the mode changes).

Also, merged in changes from #4414 which has added formatted milliseconds into the duration format, this will prevent the duplicate keys error caused from the menuApi (as names were used for keys).

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-08-22 19:08 UTC, ozyx requested changes
One small change requested, and I found a bug while doing some local testing:

1. Start a fresh instance of Open MCT w/ Local Storage
2. Switch to realtime mode
3. Go to History, you'll see one entry which looks like a Fixed Time history entry erroneously converted to realtime history
4. Click it, see realtime bounds change
5. Switch to Fixed time mode
6. It's 2075, flying cars materialize around you

2022-08-22 19:08 UTC, ozyx commented on src/plugins/timeConductor/ConductorHistory.vue
> +        let isFixedTime = this.openmct.time.clock() === undefined;
We can remove this declaration and just put it in the return, see below

2022-08-22 19:56 UTC, unlikelyzero commented
@jvigliotta we should stub out the expected behavior here.

2022-08-22 19:58 UTC, jvigliotta commented
> 

I had written something up, we can compare, sorry was working on fixes!

2022-08-23 16:35 UTC, ozyx approved these changes
LGTM

2022-08-23 16:36 UTC, merged