4417 fix codeql issues
nasa/openmct pull request #5793
Opened 2022-09-20 15:29 UTC by michaelrogers

Closes 

### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-09-20 20:30 UTC, unlikelyzero requested changes
These changes look great!

Can you update our relevant documentation with why these matter?

Also, can you create a calendar event/ticket to remove LGTM in december 2022? It looks like it's shutting down

2022-09-21 18:34 UTC, unlikelyzero commented
@michaelrogers it looks like app.js will be removed sooner than I thought. We should wait until https://github.com/nasa/openmct/pull/5797 is merged and then updated accordingly

2022-10-03 20:05 UTC, akhenry commented
app.js has been removed. Can we move ahead with this?

2022-10-07 16:20 UTC, unlikelyzero approved these changes
This looks great. We just need to ignore `**/*.spec.js` changes, and this is gtg

2022-10-07 16:30 UTC, merged