test(e2e): unique names for created objects by default
nasa/openmct pull request #5945
Opened 2022-11-03 18:13 UTC by ozyx

Contributes towards #5513  

### Describe your changes:

- Updates `createDomainObjectWithDefaults()` appAction to generate a unique name for the object unless otherwise specified.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2022-11-04 16:56 UTC, unlikelyzero approved these changes

2022-11-05 00:41 UTC, unlikelyzero commented on e2e/appActions.js
> +    const notesInput = page.locator('form[name="mctForm"] textarea[type="text"] >> nth=0');
if you have some time, can you figure out how to remove the nth locator and use something like "notes area"

2022-11-05 00:45 UTC, unlikelyzero commented on e2e/baseFixtures.js
> +    page: async ({ page, failOnConsoleError }, use, testInfo) => {
We should move this into appActions. The baseFixtures fixture is designed to disappear as native functionality is added to the `@playwright/test` or plugin ecosystem.

In this case, the testnotes function is specific to open mct

2022-11-05 00:45 UTC, unlikelyzero commented on e2e/helper/notebookUtils.js
> +async function dragAndDropEmbed(page, notebookObject) {
wow

2022-11-05 00:46 UTC, unlikelyzero commented on e2e/tests/framework/generateVisualTestData.e2e.spec.js
> +    await page.locator('li[role="menuitem"]:has-text("Sine Wave Generator")').click();
nice

2022-11-05 00:51 UTC, unlikelyzero commented on e2e/tests/functional/search.e2e.spec.js
> +    const redFolder = await createDomainObjectWithDefaults(page, {
nice

2022-11-05 19:12 UTC, unlikelyzero commented on e2e/tests/functional/search.e2e.spec.js
> +    const redFolder = await createDomainObjectWithDefaults(page, {
nice

2022-11-05 19:18 UTC, unlikelyzero requested changes
Everything looks amazing, but we should move page.testNotes out of baseFixtures and into appActions. I know this won't be a clean implementation.

baseFixtures should only contain functionality which extends the base capabilities of playwright with the intent to remove our custom functions over time

2022-11-07 18:33 UTC, ozyx commented
> baseFixtures should only contain functionality which extends the base capabilities of playwright with the intent to remove our custom functions over time

100% agree. Maybe we can move this into `pluginFixtures` instead, so we won't need to modify the function signature. I'll play around with it a bit and see what makes sense. I'm trying to avoid having to pull in the `testInfo` fixture and pass it along to `createDomainObjectWithDefaults` in every single test that creates an object.

2022-11-07 23:13 UTC, unlikelyzero commented on src/api/menu/components/Menu.vue
> +                    :class="[action.cssClass, action.isDisabled ? 'disabled' : '']"
i don't know enough about this change to review this. You should quickly ping a css wiz

2022-11-07 23:23 UTC, unlikelyzero approved these changes

2022-11-07 23:50 UTC, merged