Allow customizing multiple y axes
nasa/openmct pull request #6095
Opened 2023-01-04 18:39 UTC by shefalijoshi

Closes #5788 

### Describe your changes:

- Change the YAxis Form to allow updating more than 1 y axis
- Change the View-only plot options to display multiple visible y axes
- Ensure changing the y axis key works correctly for each y axis
- Ensure saved configurations are loaded for multiple y axes

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-01-10 00:53 UTC, ozyx requested changes
Awesome! Smoke tested and I am able to change the various configurations for each individual Y Axis, including labels which are now reactive. I've left some comments, mostly open questions and readability suggestions.

2023-01-17 14:39 UTC, shefalijoshi commented on src/plugins/plot/inspector/forms/YAxisForm.vue
> +                                path: `${this.getPrefix()}.${formKey}`,
No, the `configuration` part is attached elsewhere.

2023-01-17 14:40 UTC, shefalijoshi commented on src/plugins/plot/inspector/PlotOptionsBrowse.vue
> +            :key="`yAxis-${index}`"
I don't think so. I've never seen an error from Vue about using the same key in a different html hierarchy.

2023-01-17 14:44 UTC, shefalijoshi commented on src/plugins/plot/inspector/PlotOptionsBrowse.vue
> +                <div class="grid-cell value">{{ yAxis.label ? yAxis.label : "Not defined" }}</div>
These are still reactive but now that we are going over a list of yAxes, we need to print it per yAxis.

2023-01-17 14:45 UTC, shefalijoshi commented on src/plugins/plot/inspector/PlotOptionsBrowse.vue
> +        yAxesIds() {
Done.

2023-01-17 14:46 UTC, shefalijoshi commented on src/plugins/plot/inspector/PlotOptionsEdit.vue
> +            const yAxisId = plotSeries.get('yAxisId');
Done.

2023-01-17 14:47 UTC, shefalijoshi commented on src/plugins/plot/pluginSpec.js
> +            yAxisElement.$emit('yKeyChanged', 'test-key', 1);
Done.

2023-01-17 14:48 UTC, shefalijoshi commented on src/plugins/plot/overlayPlot/pluginSpec.js
> +                it('shows multiple yAxis options', () => {
I intentionally didn't make it 3 because I want it to go through the path where it only shows yAxes with series present.

2023-01-17 14:49 UTC, shefalijoshi commented on src/plugins/plot/overlayPlot/pluginSpec.js
> +                    expect(config.additionalYAxes[1].get('logMode')).toEqual(true);
I don't think that's necessary, a visual e2e test could do that.

2023-01-17 14:52 UTC, shefalijoshi commented on src/plugins/plot/inspector/PlotOptionsEdit.vue
> +            const foundYAxis = this.yAxes.find(yAxis => yAxis.id === yAxisId);
Done

2023-01-17 14:53 UTC, shefalijoshi commented on src/plugins/plot/inspector/PlotOptionsBrowse.vue
> +            if (this.config) {
Ideally, no. But this is informational, so we don't want everything to crash if the config doesn't exist and these properties are not displayed.

2023-01-17 17:51 UTC, ozyx approved these changes
LGTM!

2023-01-17 18:09 UTC, merged