feat: Support thumbnails in ImageryView and ImageryTimeView
nasa/openmct pull request #6132
Opened 2023-01-18 00:00 UTC by ozyx

Closes #5931 

### Describe your changes:

Prefer to use image thumbnail urls if provided via metadata in imageHistory and the imagery timestrip view.

The other half of this PR is implementing thumbnail support on the `openmct-yamcs` side (providing thumbnail URLs in metadata).

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-01-18 22:33 UTC, akhenry requested changes
Beautiful! No notes. Just needs a test.

Thanks!

2023-01-18 22:33 UTC, akhenry commented on src/plugins/imagery/components/ImageryTimeView.vue
> +            imagery.forEach(imageElm => {
Thank you

2023-01-20 23:05 UTC, akhenry approved these changes

2023-01-21 17:34 UTC, ozyx commented
@akhenry Added thumbnail support to Example Imagery and updated/added unit and e2e tests

2023-01-21 19:25 UTC, merged