Inspector tabs
nasa/openmct pull request #6137
Opened 2023-01-18 20:25 UTC by davetsay

Closes #6118

### Describe your changes:
* register all hardcoded inspector views with inspectorViewRegistry
* views get their own tabs
* tabs have logic to hide/show based on `selection` and `isEditing` (only for now)

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-01-18 23:02 UTC, ozyx requested changes
Just a couple minor comments. This is looking really awesome.

2023-01-19 17:27 UTC, davetsay commented on src/plugins/filters/FiltersInspectorViewProvider.js
> +                const object = selection?.[0]?.[0]?.context?.item;
i love how you clean up code you didn't write @ozyx .

Done!

2023-01-19 17:31 UTC, davetsay commented on src/plugins/inspectorViews/elements/ElementsPool.vue
> +            if (this.domainObject) {
good catch. left over from the refactor. removed.

2023-01-19 19:59 UTC, ozyx approved these changes
LGTM!

2023-01-19 19:59 UTC, ozyx commented on src/plugins/filters/FiltersInspectorViewProvider.js
> +                        return hasPersistedFilters || hasGlobalFilters;
nice!

2023-01-20 18:30 UTC, charlesh88 reviewed
- [ ] @charlesh88 to do some visual sweetening on the tabs.

2023-01-21 01:06 UTC, charlesh88 commented
HIGH PRIORITY: when editing a layout or something else with style-able sub-objects, do not switch the tab when a user clicks something else - this is a must-have. Secondarily, I think this should be case for anything, like navigating amongst domain objects.

We need to keep the current tab key in memory, and if a newly selected object also supports that key, don’t switch - only switch if the new object doesn’t have that key.

2023-02-23 19:38 UTC, davetsay commented
this should be good to go again. I just need to confirm with you that merge conflict resolution didn't bork annotations, @scottbell.

2023-02-28 23:25 UTC, davetsay commented
@scottbell , when you get a chance. I'll need some help in knowing if I borked annotations

2023-03-01 08:45 UTC, scottbell approved these changes
Tested tags against notebooks, stacked plots, overlay plots, and search - looks good, Dave!

2023-03-01 08:45 UTC, scottbell commented on src/plugins/inspectorViews/annotations/AnnotationEditor.vue
> +/*****************************************************************************
We can remove this file until we get text annotations implemented.

2023-03-06 22:11 UTC, merged