Compass rose fix
nasa/openmct pull request #6318
Opened 2023-02-10 00:44 UTC by davetsay

Closes #6257

### Describe your changes:
* Fixes equipment detached from camera
* Fixes rotation of compass dial in relation to non-gimballing cameras
* Fixes compass HUD display for non-gimballing cameras

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-02-10 01:01 UTC, ozyx requested changes
One minor comment, pointing out something that could evaluate to `NaN` and bypass fallback code

2023-02-10 15:16 UTC, akhenry requested changes
Looks good to me. Just the issue that @ozyx  highlighted, which I think we need to address.

2023-02-10 15:23 UTC, davetsay commented on src/plugins/imagery/components/Compass/Compass.vue
> +                : rotate(this.heading, -this.transformations?.rotation ?? 0);
thanks!

2023-02-10 15:28 UTC, davetsay commented on src/plugins/imagery/components/Compass/Compass.vue
> +                : rotate(this.heading, -this.transformations?.rotation ?? 0);
also made the change that transformations will always be defined here.

2023-02-10 15:46 UTC, akhenry commented
Found an issue in testing. If I change the bounds while I'm on an image the image reloads but the compass does not.

1. Navigate to an image with bounds set such that at least one image is in bounds (if necessary)
2. Expand the time window
3. Observe that the image reloads but the compass does not.

2023-02-10 18:11 UTC, charlesh88 approved these changes
From my perspective (non-coding) LGTM.

2023-02-13 19:18 UTC, akhenry approved these changes
LGTM

2023-02-13 19:20 UTC, ozyx approved these changes

2023-02-13 19:28 UTC, merged