First attempt at DeploySentinel
nasa/openmct pull request #6398
Opened 2023-03-06 22:18 UTC by unlikelyzero

Closes 

### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-03-07 18:31 UTC, unlikelyzero commented on package.json
> +    "test:clean": "rm -rf ./coverage ./html-test-results ./test-results ./nyc_output/",
driveby

2023-04-04 22:05 UTC, ozyx requested changes
Looks good overall! Just have a few small suggestions

2023-04-04 22:05 UTC, ozyx commented on e2e/tests/functional/plugins/notebook/notebookWithCouchDB.e2e.spec.js
> +    await page.waitForSelector(`[aria-label="Tag"]:has-text("${tagName}")`, {state: 'hidden'});
should we make this an assertion instead?
```js
expect(page.locator(`[aria-label="Tag"]:has-text("${tagName}")`).toBeHidden();
```

2023-04-04 22:05 UTC, ozyx commented on e2e/tests/functional/plugins/notebook/notebookWithCouchDB.e2e.spec.js
> +        page.waitForSelector(`[aria-label="Tag"]:has-text('${tagName}')`)
Convert to assertion also?

```js
expect(page.locator(`[aria-label="Tag"]:has-text("${tagName}")`).toBeVisible();
```

2023-04-04 22:22 UTC, ozyx commented on package.json
> +    "test:clean": "rm -rf ./coverage ./html-test-results ./test-results ./nyc_output/",
should be `./.nyc_output` ?

2023-04-05 01:40 UTC, ozyx approved these changes
LGTM

2023-04-05 09:45 UTC, scottbell approved these changes

2023-04-05 13:25 UTC, merged