Changed tooltip text to be Shift+Alt drag to pan
nasa/openmct pull request #6417
Opened 2023-03-13 20:18 UTC by michaelrogers

Closes 

### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-03-13 20:54 UTC, ozyx requested changes
Cool! One small question

2023-03-13 20:54 UTC, ozyx commented on e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
>  const panHotkey = process.platform === 'linux' ? ['Control', 'Alt'] : ['Alt'];
Has the actual hotkey been changed yet? We should update the `panHotkey` if true

2023-03-14 17:04 UTC, ozyx approved these changes
LGTM

2023-03-14 19:45 UTC, unlikelyzero approved these changes

2023-03-15 03:42 UTC, merged