[Greedy LAD] Add new functionality for Latest Available Data views
nasa/openmct pull request #6432
Opened 2023-03-15 05:15 UTC by jvigliotta

Closes 

### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-03-15 18:21 UTC, unlikelyzero commented
@jvigliotta do you have an issue for this bad boy?

2023-03-15 23:22 UTC, akhenry requested changes
Looks really good, thank you.

I don't think the notifications are scalable. We have displays with like 50 LAD views in them, so I think we need to ship this initially with no notifications until we come up with a better UI solution to this.

I _suspect_ that we can simplify things by creating a separate class for handling LAD telemetry, like a `LADTelemetryHandler` or something, but that's a problem for another time.

2023-03-15 23:26 UTC, jvigliotta commented
> @jvigliotta do you have an issue for this bad boy?

I do not! I'll work with @akhenry to get one, I don't have access to the original

2023-03-16 18:12 UTC, akhenry requested changes

2023-03-16 18:12 UTC, akhenry commented on src/api/telemetry/TelemetryCollection.js
> +            this.dataOutsideTimeBounds = false;
Is this flag actually used for anything any more?

2023-03-16 18:41 UTC, jvigliotta commented
follow up for tests: #6451 6451

2023-03-17 01:58 UTC, akhenry approved these changes

2023-03-17 02:12 UTC, merged