Clicking a plot annotation should pause the plot
nasa/openmct pull request #6446
Opened 2023-03-16 09:43 UTC by scottbell

Closes #6443 #6214 #6458

### Describe your changes:
Pause plot when clicking on plot annotation search result. Get rid of rectangles when resuming realtime data.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-03-16 20:51 UTC, khalidadil approved these changes

2023-03-16 21:12 UTC, shefalijoshi requested changes

2023-03-17 19:10 UTC, shefalijoshi approved these changes

2023-03-17 19:10 UTC, shefalijoshi commented
Looks good!

2023-03-17 19:12 UTC, merged