Simple text export of Notebook
nasa/openmct pull request #6510
Opened 2023-03-27 14:58 UTC by scottbell

Closes #6435 

### Describe your changes:
This is a simple text export of a Notebook object into markdown. It iterates through all the sections, pages, and entries and produces a markdown text of the result. Things we may like to add before merging:

- Metadata: in particular, who created the entry, when it was created, when it was modified, etc.
- Tags (with the above metadata?)
- Images
- Snapshots

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-03-27 15:01 UTC, scottbell commented
Here's the action in action:

https://user-images.githubusercontent.com/9853862/227980150-de3f9dec-14fc-4c0e-9098-45ab616f829c.mov

And here's the resultant markdown text output:

[Test Notebook.md](https://github.com/nasa/openmct/files/11080109/Test.Notebook.md)

2023-03-30 17:00 UTC, ozyx requested changes
LGTM! Let's just put in some stubs for further Notebook text export tests.

2023-03-30 17:00 UTC, ozyx commented on e2e/tests/functional/plugins/notebook/notebook.e2e.spec.js
> +        expect(exportedText).toContain('Foo bar entry');
We should expand this test to check against the exact text output of a notebook. We should also have tests for checking notebooks with/without tags, metadata, and snapshots (when applicable).

I don't think the PR should be blocked by this, so let's put in some quick stubs?

2023-03-30 17:32 UTC, ozyx approved these changes

2023-03-30 17:44 UTC, merged