Timelist bug fixes
nasa/openmct pull request #6661
Opened 2023-05-11 21:36 UTC by shefalijoshi

Closes #6536 

### Describe your changes:
Ensure timelist scrolling happens correctly for clock as well as fixed time - sort the list first, and wait for the DOM to be updated before scrolling.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-05-16 16:42 UTC, ozyx requested changes
I've left a couple small suggestions. I have a couple of questions as well, which need @charlesh88 's input:

1. 
![image](https://github.com/nasa/openmct/assets/9259993/b6af0a9d-94f6-4862-9bb8-6ef51a564ddf)

Looking at the above screenshot, you can see one activity that has passed its "end" time already, two which are currently active, and the rest which are yet to reach their "start" time. The time displayed for activities which have yet to occur is prefixed with a `+`, whereas activities which have already completed are prefixed with a `-`.

When I think of countdowns, I think T-Minus and T-Plus. This seems to reverse that (of course, I'm a layman with regards to rocketry so I could be totally wrong here). Is this the intended design?

2. 

https://github.com/nasa/openmct/assets/9259993/25292dfb-40c8-49a4-845d-f00424d836fd

Here I am navigating to a Timelist with a Plan that has two active activities. Upon navigation, the autoscroll will scroll down so that the first activity is out of view. The [bug description](https://github.com/nasa/openmct/issues/6536) states that "The Time List view is supposed to scroll to keep activities that are close to "now" centered in the available view." Does this mean that we should be scrolling so that the earliest active activity appears in the view, instead of the current behavior?

2023-05-16 22:02 UTC, charlesh88 commented
> When I think of countdowns, I think T-Minus and T-Plus. This seems to reverse that (of course, I'm a layman with regards to rocketry so I could be totally wrong here). Is this the intended design?

This appears to be the opposite of the original design: https://www.figma.com/file/oiWdYndFhxxkBTGkM9vWAv/Timelist-View-v1.0?type=design&node-id=0%3A1&t=fFwvfgmQBSyvY5uK-1. Basically, it's supposed to be like this:

- "Past" activities (start time < end time < now) should count UP from their END time with a "+" symbol.
- Current activities (start time < now < end time) should be counting DOWN to their END time, with a "-".
- Future activities (now < start time < end time) should be counting DOWN to their START time, with a "-".

The real thing is this: when the number are going up, it should be a "+" sign. When they're going down, they should use a "-".

2023-05-16 22:19 UTC, charlesh88 commented
> Here I am navigating to a Timelist with a Plan that has two active activities. Upon navigation, the autoscroll will scroll down so that the first activity is out of view. The [bug description](https://github.com/nasa/openmct/issues/6536) states that "The Time List view is supposed to scroll to keep activities that are close to "now" centered in the available view." Does this mean that we should be scrolling so that the earliest active activity appears in the view, instead of the current behavior?

I don't understand from your video why the second scroll event occurs. What's supposed to happen is that the view should scroll to keep current activities "centered" in the vertical space of the scrolled area. That's what appears to happen at first, but then a scroll occurs that hides the current activity. If that's what happened, that's not what's intended.

Can we do a screenshare.

2023-05-17 17:37 UTC, ozyx commented
After discussing with Charles it looks like https://github.com/nasa/openmct/issues/6657 with regards to the timestamp is correctly fixed, although the `+` and the `-` signs need to be reversed (e.g. `+` prefixed timestamps should be counting down and `-` prefixed timestamps should be counting up). 
One other change @charlesh88 requested is to remove the milliseconds from the timestamps in the timelist, which should be achievable with just an edit to the moment format string.

There is an issue with the fix for https://github.com/nasa/openmct/issues/6536 in Display Layouts, where it seems that the scroll is not taking into account the frame size of the container, causing it to scroll where active activities may be out of view if embedded in a layout.

2023-05-22 16:41 UTC, shefalijoshi commented on src/plugins/timelist/Timelist.vue
>              this.planActivities = activities.sort(this.sortByStartTime);
Yep. Removing.

2023-05-31 17:33 UTC, shefalijoshi commented
> I've left a couple small suggestions. I have a couple of questions as well, which need @charlesh88 's input:
> 
> 
> ![image](https://user-images.githubusercontent.com/9259993/238712246-b6af0a9d-94f6-4862-9bb8-6ef51a564ddf.png)
> 
> Looking at the above screenshot, you can see one activity that has passed its "end" time already, two which are currently active, and the rest which are yet to reach their "start" time. The time displayed for activities which have yet to occur is prefixed with a `+`, whereas activities which have already completed are prefixed with a `-`.
> 
> When I think of countdowns, I think T-Minus and T-Plus. This seems to reverse that (of course, I'm a layman with regards to rocketry so I could be totally wrong here). Is this the intended design?
> 
> 
> Screen.Recording.2023-05-16.at.9.28.26.AM.mov
> 
> Here I am navigating to a Timelist with a Plan that has two active activities. Upon navigation, the autoscroll will scroll down so that the first activity is out of view. The [bug description](https://github.com/nasa/openmct/issues/6536) states that "The Time List view is supposed to scroll to keep activities that are close to "now" centered in the available view." Does this mean that we should be scrolling so that the earliest active activity appears in the view, instead of the current behavior?

@ozyx It looks like the current activity scrolls into view, yes? If so, this is intended behavior. If you manually scroll it, it should bounce back to the *current* activity after 1 minute of idling.

2023-05-31 23:26 UTC, ozyx approved these changes
This is looking good! I'm still seeing the issue regarding #6536 where the time list will scroll some current activities out of view if in a display layout (see quote below for more details), but in the interest of getting these changes in and in front of other eyes I'm going to approve.

The PR just needs a `lint:fix` and a small change against a failing unit test before it can merge

>  Screen.Recording.2023-05-16.at.9.28.26.AM.mov 
> Here I am navigating to a Timelist with a Plan that has two active activities. Upon navigation, the autoscroll will scroll down so that the first activity is out of view. The [bug description](https://github.com/nasa/openmct/issues/6536) states that "The Time List view is supposed to scroll to keep activities that are close to "now" centered in the available view." Does this mean that we should be scrolling so that the earliest active activity appears in the view, instead of the current behavior?

2023-06-02 18:09 UTC, unlikelyzero requested changes
Let's sync on the test coverage we want to add this this one. This issue is being track by Masoud

2023-06-05 18:38 UTC, charlesh88 submitted a review, later dismissed
Fixes for no msecs and to/from/durations all look great. The fix for #6536 does not appear to be working, however, when there's no current activity. The view needs to center on "now" even when an activity isn't current.

**Current activity available, view centering properly**
![Screen Shot 2023-06-05 at 11 16 59 AM](https://github.com/nasa/openmct/assets/1056412/83ae1549-b6c2-4844-8043-1d7e35e6c271)

**No current activity - what the view _should_ be doing but isn't**
![Screen Shot 2023-06-05 at 10 58 24 AM](https://github.com/nasa/openmct/assets/1056412/d0d9b605-5efb-4ee1-8a72-7b5d5cc04ed2)


**No current activity, view scrolls to top automatically**
![Screen Shot 2023-06-05 at 10 58 14 AM](https://github.com/nasa/openmct/assets/1056412/75602730-294c-4d2a-8bc2-a85186171a39)

Synthetic plan used for testing:
[Plan Gen 2023-06-05.1.json.zip](https://github.com/nasa/openmct/files/11655639/Plan.Gen.2023-06-05.1.json.zip)

2023-06-07 13:23 UTC, shefalijoshi commented
@charlesh88 Please re-review the fix for the final issue mentioned here.

2023-06-16 18:56 UTC, rukmini-bose commented
Just reviewed this. The last change looks like its been fixed!

2023-06-16 18:56 UTC, rukmini-bose approved these changes
This looks good! Last change looks like it's been fixed.

2023-06-16 19:05 UTC, unlikelyzero approved these changes

2023-06-16 19:46 UTC, merged