Feature/issue 6656
nasa/openmct pull request #6756
Opened 2023-06-23 17:34 UTC by khalidadil

Closes #6656

### Describe your changes:

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [X] Changes address original issue?
* [X] Tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [X] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-06-23 18:08 UTC, ozyx commented on src/api/tooltips/ToolTipAPI.js
> +   * @property {string} tooltipLocation location to show the tooltip relative to the parentElement
We should expose these options as an enum-like collection of consts, kind of like how the AnnotationAPI has annotationTypes?

2023-07-06 18:55 UTC, charlesh88 commented
Great stuff! I've pushed some tweaks to the CSS. As discussed, if we could add to Tabs views that'd be wonderful.

2023-07-13 23:40 UTC, khalidadil commented on src/plugins/LADTable/components/LADRow.vue
> +      {{ domainObject.name }}
I had to add spacing here because of linting rules, which resulted in needing to trim the spaces from a test.

2023-07-13 23:40 UTC, khalidadil commented on src/plugins/LADTable/pluginSpec.js
> +      const rowName = parent.querySelector(TABLE_BODY_FIRST_ROW_FIRST_DATA).innerText.trim();
Trimming extra spacing

2023-07-14 01:03 UTC, ozyx requested changes
Just a few minor comments. We should also make sure to document this feature somewhere, since it requires a hover + mod key, it may not be immediately discoverable.

2023-07-14 01:23 UTC, khalidadil commented on src/plugins/conditionWidget/components/ConditionWidget.vue
> +    @mouseover.ctrl="showToolTip"
I got it mostly working with a custom directive after we talked last time, but I felt like it added a lot of template bloat but definitely something we could consider

2023-07-14 01:24 UTC, khalidadil commented on src/plugins/conditionWidget/components/ConditionWidget.vue
> +      const { BELOW } = this.openmct.tooltips.TOOLTIP_LOCATIONS;
yeah, it wasn't so ugly after destructuring!

2023-07-14 01:29 UTC, khalidadil commented on src/api/tooltips/tooltipMixins.js
> +    async getTelemetryPath(telemetryIdentifier) {
Works for me!

2023-07-14 01:30 UTC, khalidadil commented on src/api/tooltips/ToolTipAPI.js
> +   * private
good call!

2023-07-14 01:37 UTC, khalidadil commented on src/api/tooltips/ToolTipAPI.js
> +   * A description of option properties that can be passed into the overlay
I think I got it! Let me know if there's anything still missing

2023-07-14 01:38 UTC, khalidadil commented
> Just a few minor comments. We should also make sure to document this feature somewhere, since it requires a hover + mod key, it may not be immediately discoverable.

I'll ask Charles where the best place to document this would be and include it when I add more tests

2023-07-14 04:36 UTC, ozyx commented on src/plugins/conditionWidget/components/ConditionWidget.vue
> +    @mouseover.ctrl="showToolTip"
oh, interesting. yeah! let's chat when we both have more cycles

2023-07-14 04:37 UTC, ozyx approved these changes
LGTM! 🚀🚀🚀

2023-07-14 04:38 UTC, merged