Toggle between showing aggregate stacked plot legend or per-plot legend
nasa/openmct pull request #6758
Opened 2023-06-23 21:09 UTC by shefalijoshi

Closes VIPERRQSTS-239

### Describe your changes:
New option to show/hide stacked plot aggregate legend - defaulted to …not show.
Use the Plot component in the StackedPlotItem component for simplicity
Add logic to how/hide per plot legends as needed.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-06-27 17:35 UTC, rukmini-bose approved these changes
This looks good to me!

2023-07-03 22:52 UTC, jvigliotta requested changes
Two small changes and 2 issues I found. It seams staleness styling is a little messed up now (example images) and the other issue is that position of the legend doesn't seem to be working anymore?

Before:
![Screenshot 2023-07-03 at 3 47 57 PM](https://github.com/nasa/openmct/assets/12013460/e07e2ebf-0112-49f5-850e-4d0f13cf1a26)

After:
![Screenshot 2023-07-03 at 3 46 59 PM](https://github.com/nasa/openmct/assets/12013460/771e4df3-21a3-4d31-9a1c-4e00045bfd7e)

This is the same plot, but you can see the position is set to bottom which is working in the older version. The issue with styling seems to be the border is missing and the legend item styling seems off.

2023-07-03 22:52 UTC, jvigliotta commented on src/plugins/plot/chart/MctChart.vue
> +        this.showLimitLineLabels?.seriesKey && this.showLimitLineLabels.seriesKey === seriesKey
Think you can simplify this: `return this.showLimitLineLabels?.seriesKey  === seriesKey`

2023-07-03 22:52 UTC, jvigliotta commented on src/plugins/plot/Plot.vue
>        // hideExportButtons: false
I think I _may_ have commented this out, either way we can probably remove it now

2023-07-07 18:07 UTC, shefalijoshi commented
> Two small changes and 2 issues I found. It seams staleness styling is a little messed up now (example images) and the other issue is that position of the legend doesn't seem to be working anymore?
> 
> Before: ![Screenshot 2023-07-03 at 3 47 57 PM](https://user-images.githubusercontent.com/12013460/250671930-e07e2ebf-0112-49f5-850e-4d0f13cf1a26.png)
> 
> After: ![Screenshot 2023-07-03 at 3 46 59 PM](https://user-images.githubusercontent.com/12013460/250671932-771e4df3-21a3-4d31-9a1c-4e00045bfd7e.png)
> 
> This is the same plot, but you can see the position is set to bottom which is working in the older version. The issue with styling seems to be the border is missing and the legend item styling seems off.

Positioning of legend for child plots within a stacked plot is blocked intentionally.

2023-07-11 17:41 UTC, rukmini-bose requested changes
It looks like the staleness bux is _half_ fixed. While we now see the correct border an icon at the bottom left of the plot, we also see the icon on the legend, which shouldn't be there. I believe that in the legend, the data point should only be highlighted in cyan. 

What we are seeing (notice the legend): 
<img width="1493" alt="Screen Shot 2023-07-11 at 10 38 38 AM" src="https://github.com/nasa/openmct/assets/48999852/e186c77c-ed12-48ba-afb4-bca884c337e8">

What it should look like: 
<img width="189" alt="Screen Shot 2023-07-11 at 10 40 22 AM" src="https://github.com/nasa/openmct/assets/48999852/7d2a1da4-1029-462b-83ba-43ba68086028">

In addition, I had a thought– if users cannot change the positioning of the legend when we are in the "per plot" setting (which was a conscious UI decision), can we just hide that setting unless the user toggles off the setting? Otherwise, I can see how it can cause confusion to a user. 

Other than that, all looks good!

2023-07-11 18:30 UTC, jvigliotta commented
I didn't see anything other than what @rukmini-bose pointed out. I did notice, you only get the messed up icons when "per plot" legend is selected. It's fine when it's all in one line.

2023-07-11 19:39 UTC, rukmini-bose approved these changes
This looks good! For a future enhancement, let’s try to disable the option for users to change the position of the legend if it’s per plot. LGTM, good job :))

2023-07-11 19:46 UTC, jvigliotta approved these changes
Nice work!

2023-07-11 23:16 UTC, merged