fix: use `loadDelay` generator setting in subscriptions as well
nasa/openmct pull request #6918
Opened 2023-08-10 21:41 UTC by ozyx

Closes #6917 

### Describe your changes:

Uses the `loadDelay` value specified on Sine Wave Generators to delay its realtime data in addition to historical requests. Vue 3 improved reactivity is causing the conditionSet to update when the SWG receives new realtime data, which was happening instantly because we weren't delaying realtime data. This fixes the e2e test and correctly tests the case where telemetry is not outputting data.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-08-11 18:36 UTC, unlikelyzero requested changes

2023-08-11 20:36 UTC, khalidadil commented on example/generator/WorkerInterface.js
> +        setTimeout(() => cb(message.data), Math.max(loadDelay, 0));
Is there any way to do this without this `setTimeout`?

2023-08-11 20:59 UTC, khalidadil commented on example/generator/WorkerInterface.js
> +        setTimeout(() => cb(message.data), Math.max(loadDelay, 0));
nvm, understood this is to apply the loadDelay to SWGs in realtime subscriptions

2023-08-14 05:36 UTC, unlikelyzero commented on e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
> +  test('ConditionSet should output blank instead of the default value when no telemetry available', async ({
tried to make it clearer to those without the context within the context within the context of the OG issue

2023-08-14 05:36 UTC, unlikelyzero commented on e2e/tests/functional/plugins/conditionSet/conditionSet.e2e.spec.js
> +    const exampleTelemetry = await createExampleTelemetryObject(page);
Moved to exampleTelemetry object.

todo: update telemetry object with Load delay for this specific scenario

2023-08-14 17:33 UTC, unlikelyzero approved these changes
If you can just add a few more comments to the reasoning behind the assertions

2023-08-14 19:04 UTC, merged