feat(eslint): sort import rule
nasa/openmct pull request #6939
Opened 2023-08-15 17:09 UTC by evenstensberg

#6888

### Describe your changes:
Rule to sort imports.

https://github.com/lydell/eslint-plugin-simple-import-sort

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-08-28 20:01 UTC, evenstensberg commented
This should be added after UMD -> ESM

2023-08-30 23:46 UTC, ozyx commented
> This should be added after UMD -> ESM

Do you think it would cause us any issues if we add it before this is completed? This is great and I would like to incorporate it into our eslint config.

2023-08-30 23:47 UTC, ozyx requested changes

2023-08-30 23:47 UTC, ozyx commented on package.json
> +    "eslint-plugin-simple-import-sort": "^10.0.0",
Let's go ahead and pin this to the latest version so dependabot can manage it

2023-08-31 14:33 UTC, evenstensberg commented
@ozyx You can run the plugin without any issues (se eslintrc for rules to toggle). This plugin is very simple, as it says. 

I'd rather have a look at  https://github.com/import-js/eslint-plugin-import if that is ok for you? It's more extensive and checks more than just the import order

2023-08-31 18:05 UTC, evenstensberg commented
@ozyx PTAL! Atm I've configured to only have warnings on import/export rules. You can fix those pretty easily.

2023-08-31 20:39 UTC, ozyx approved these changes
Good stuff. Thank you!

2023-08-31 20:40 UTC, merged