Fix and re-enable disabled unit test suites
nasa/openmct pull request #6990
Opened 2023-08-24 20:29 UTC by ozyx

Closes #7016
Closes #7019  

### Describe your changes:

Fixes and re-enables most unit test suites that were disabled while we were working through the Vue 3 compat upgrade. Fixes a couple of issues and adds e2e coverage for suites we were unable to re-enable.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-08-31 08:36 UTC, scottbell requested changes
Good stuff @ozyx! Changes work well:


https://github.com/nasa/openmct/assets/9853862/1d76f158-f128-4af3-90a2-fd649720f954


https://github.com/nasa/openmct/assets/9853862/fab9d97e-3575-4d4d-aa7d-a068bbb51b81

Had a small suggestion about code comments, but otherwise looks good.

2023-08-31 08:36 UTC, scottbell commented on src/ui/layout/pane.vue
> +    this.openmct.router.on('change:params', this.handleHideUrl.bind(this));
clean!

2023-08-31 08:36 UTC, scottbell commented on src/plugins/timer/components/Timer.vue
> +      if (Number.isNaN(Date.parse(this.configuration.timestamp))) {
Should we add a comment here why the timestamp might not be a number?

2023-08-31 16:07 UTC, ozyx commented
> Good stuff @ozyx! Changes work well:
>  timers.mov 
> Had a small suggestion about code comments, but otherwise looks good.

Hmm.. in your Timer video, that behavior doesn't seem quite right. You can see in the inspector the Target is initially undefined? Then when we hit play, it resets the target completely. Will look into this as well.

2023-08-31 18:31 UTC, unlikelyzero commented on e2e/tests/functional/plugins/timer/timer.e2e.spec.js
> +  test.use({
Let's document this in our e2e best practices

2023-08-31 18:35 UTC, unlikelyzero commented on src/plugins/timer/components/Timer.vue
> +        return Date.parse(this.configuration.timestamp);
isn't this covered by your timer.e2e.spec.js?

2023-08-31 18:42 UTC, unlikelyzero commented on e2e/tests/functional/plugins/timer/timer.e2e.spec.js
> +  const timerElement = page.locator('.c-timer');
let's add the a11y property to this

2023-09-01 16:16 UTC, ozyx commented on e2e/appActions.js
> +  await page.goto(`${parentUrl}`);
it shouldn't be here and it was only working because hideTree was broken

2023-09-01 23:44 UTC, unlikelyzero commented on e2e/README.md
> +- Overriding the Clock
Overriding the Browser's Clock to control time based elements

2023-09-01 23:45 UTC, unlikelyzero commented on e2e/appActions.js
> +  await page.goto(`${parentUrl}`);
@ozyx i remember now: we put that in there to make the e2e tests faster when running on viper. If we launch with the tree closed, we load faster

2023-09-01 23:47 UTC, unlikelyzero requested changes
We need to add hideTree back to improve the speed of execution when using appActions in viper

2023-09-01 23:53 UTC, ozyx commented on e2e/appActions.js
> +  await page.goto(`${parentUrl}`);
I don't think so, this never worked after the initial navigation. My changes make it work like a real router param. Maybe we can include it somewhere else?

2023-09-03 15:25 UTC, unlikelyzero approved these changes

2023-09-05 08:44 UTC, scottbell approved these changes
Timers working well (from what I can tell!):

https://github.com/nasa/openmct/assets/9853862/55b0f8df-961a-44f0-bc94-efd06f5297b8

2023-09-05 08:53 UTC, merged