Protect against prototype pollution in import action
nasa/openmct pull request #7094
Opened 2023-09-27 19:42 UTC by davetsay

Closes #7089

### Describe your changes:
remove `__proto__` when parsing JSON from import action

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-09-28 23:16 UTC, unlikelyzero commented
Can you add a functional and negative test scenario for this in the e2e suite

2023-09-28 23:29 UTC, shefalijoshi commented on src/plugins/localStorage/LocalStorageObjectProvider.js
> +    return JSON.parse(this.getSpace(), filter__proto__);
Can we use Vue's `toRaw`utility here?
Something like:
`return JSON.parse(toRaw(this.getSpace())`

2023-09-28 23:30 UTC, shefalijoshi commented on src/plugins/importFromJSONAction/ImportFromJSONAction.js
> +    const objectTree = JSON.parse(jsonTree, filter__proto__);
Can we use Vue's toRawutility here?
Something like:
return JSON.parse(toRaw(jsonTree)

2023-09-28 23:30 UTC, shefalijoshi reviewed
Curious if we can use Vue's utility method here instead?

2023-09-29 00:31 UTC, davetsay commented
> Curious if we can use Vue's utility method here instead?

I think we should try to keep view/Vue code out of the logic paths if possible.

2023-09-29 20:09 UTC, shefalijoshi approved these changes
Looks fine!

2023-10-02 21:13 UTC, ozyx requested changes
Looks like there's a new memory leak? thus the failing perf test

2023-10-02 21:45 UTC, ozyx approved these changes

2023-10-02 21:45 UTC, davetsay commented
> Looks like there's a new memory leak? thus the failing perf test

I re-ran the tests and perf passes. I don't think this introduced a leak.

2023-10-02 21:50 UTC, merged