Only show marquee for selected item
nasa/openmct pull request #7180
Opened 2023-10-26 18:22 UTC by davetsay

Closes #7179 

### Describe your changes:
Added check to see if selection is in the currently selected layout

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-10-26 18:51 UTC, davetsay commented
Was scratching my head on this one for a bit. Was unsure why this regressed when the code didn't change much. It looks like regardless of `showMarquee` check, the marquee is further controlled by css. Something with selectors, the html structure, must have changed as a result of the Vue 3 upgrade, since Vue 2 components mounted by replacing the element, while Vue 3 does not.

@charlesh88 , do you want to look at the css, or this JS fix should work to fix.

2023-10-26 19:08 UTC, charlesh88 commented
Seeing a new problem: the selection marquee is now hidden after the first manipulation of an object, via the cursor or numeric input position and size inputs in the toolbar. The object remains selected, but the marquee isn't displayed. Another object can't be selected unless the first is deselected, or by clicking a new object twice. This is the case for all elements with 4 control handles: drawing objects, alphanumerics, nested layouts - everything _but_ the line drawing object. 

https://github.com/nasa/openmct/assets/1056412/67ae341c-8269-4fcb-be70-18909d871fbf

2023-10-27 13:42 UTC, unlikelyzero requested changes
Sync with me on how to write a test for this

2023-10-27 19:54 UTC, davetsay commented
> Seeing a new problem: the selection marquee is now hidden after the first manipulation of an object, via the cursor or numeric input position and size inputs in the toolbar. The object remains selected and it can be manipulated (moved with drag and changed via toolbar inputs), but the marquee isn't displayed. Another object can't be selected unless the first is deselected, or by clicking a new object twice. This is the case for all elements with 4 control handles: drawing objects, alphanumerics, nested layouts - everything _but_ the line drawing object.
> 
>  Display.Layout.7179.selection.marquee.lost.after.manipulation.mp4

Weird but I see it too. Will look into it. What do you think about the css? Worth fixing?

2023-10-27 19:56 UTC, davetsay commented
> Sync with me on how to write a test for this

e2e or visual? I should be good on e2e. I should put this into draft until we decide what the proper fix is.

2023-10-30 16:26 UTC, charlesh88 commented
> Weird but I see it too. Will look into it. What do you think about the css? Worth fixing?

I will take a further look.

2023-11-06 17:52 UTC, ozyx commented
> > Sync with me on how to write a test for this
> 
> e2e or visual? I should be good on e2e. I should put this into draft until we decide what the proper fix is.

probably a visual i'd think

2023-11-15 01:14 UTC, davetsay commented
> Sync with me on how to write a test for this

How'd I do?

2023-11-15 01:15 UTC, davetsay commented
@charlesh88 , somewhere I think grids also regressed. Please verify if grids are as expected.
Marquee only for selected. Grid only on parent of selected.

2023-11-15 21:41 UTC, ozyx requested changes

2023-11-15 21:41 UTC, ozyx commented on e2e/tests/visual/displayLayout.visual.spec.js
> +async function setupBaseline(page, theme, openmctConfig) {
Let's add some JSDocs here with valid types

2023-11-15 23:04 UTC, ozyx approved these changes
Nice work!

2023-11-15 23:28 UTC, unlikelyzero requested changes
I'm not seeing the test results. Let's sync first thing tomorrow

2023-11-16 01:08 UTC, unlikelyzero commented on e2e/tests/visual/displayLayout.visual.spec.js
> +  const objectViewLocator = page.locator('.c-object-view');
generally, the practice would be to improve the locator such that we don't reference this by classname

2023-11-16 18:31 UTC, unlikelyzero approved these changes

2023-11-16 18:31 UTC, merged