Add static limit values to LAD tables
nasa/openmct pull request #7193
Opened 2023-10-31 10:38 UTC by scottbell

Closes #5051 

### Describe your changes:

- Added limits to table columns
- Simplify how table headers are calculated for inspector. Allow limits to be removed

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-11-01 23:07 UTC, ozyx requested changes
Looking great! Just some minor suggestions regarding some e2e locators. Let's also sync tomorrow and get this feature-tested against VIPER

2023-11-01 23:07 UTC, ozyx commented on e2e/tests/functional/plugins/lad/lad.e2e.spec.js
> +    await page.locator('button:has-text("OK")').click();
```suggestion
  await page.getByRole('menuitem', { name: /Remove/ }).click();
  await page.getByRole('button', { name: 'OK' }).click();
```

2023-11-02 12:34 UTC, scottbell commented on e2e/tests/functional/plugins/lad/lad.e2e.spec.js
> +    await page.locator('[title="Edit"]').click();
Note, will need to change this to `page.getByLabel('Edit')` as `page.getByTitle('Edit')` resolves to both "Unlock Editing" and "Edit"

2023-11-08 17:43 UTC, ozyx approved these changes
LGTM

2023-11-08 17:57 UTC, merged