7170 inconsistent behavior with multiple annotations in imagery
nasa/openmct pull request #7261
Opened 2023-11-28 16:50 UTC by scottbell

Closes 

### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

2023-11-29 15:38 UTC, scottbell commented on src/plugins/imagery/components/AnnotationsCanvas.vue
> +        const tagEditorClassNames = [
i really don't like this!

2023-11-30 21:07 UTC, davetsay requested changes
Couple minor code cleanup suggestions. Good work

2023-11-30 21:07 UTC, davetsay commented on src/plugins/imagery/components/AnnotationsCanvas.vue
> +import _ from 'lodash';
```suggestion
import isEqual from 'lodash/isequal';
```

2023-11-30 21:07 UTC, davetsay commented on src/plugins/imagery/components/AnnotationsCanvas.vue
> +            return _.isEqual(targetDetail, toRaw(target));
```suggestion
            return isEqual(targetDetail, toRaw(target));
```
see above for explicitly importing `lodash/isequal`

2023-12-04 23:04 UTC, davetsay commented on src/plugins/inspectorViews/annotations/tags/TagEditorClassNames.js
> +const TagEditorClassNames = Object.freeze({
👍

2023-12-05 00:01 UTC, unlikelyzero commented on e2e/tests/functional/plugins/imagery/exampleImagery.e2e.spec.js
> +    await expect(page.getByText('Drilling')).toBeVisible();
nice

2023-12-05 00:01 UTC, unlikelyzero approved these changes

2023-12-05 02:33 UTC, davetsay approved these changes
Good stuff

2023-12-05 03:12 UTC, merged