Add support for multiple CouchDB databases, multiple namespaces, and `readOnly` configurations
nasa/openmct pull request #7413
Opened 2024-01-25 09:13 UTC by scottbell

Closes #7359 #7360

### Describe your changes:

Add support for multiple CouchDB databases, namespaces, and `readOnly` configurations.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

2024-01-26 21:49 UTC, ozyx approved these changes
Wow, this is awesome. I haven't tried it, but I assume this works with multiple CouchDB databases as well?

I did find one issue with search, where after the search has completed, the "loading" progress bar is still spinning permanently:


https://github.com/nasa/openmct/assets/9259993/06931601-3c5e-4062-809d-8af979ace969

I think we can spin that off into its own issue, though. I don't have any PR-blocking comments at this time! I tested locally and everything seems to work well.

2024-01-26 21:49 UTC, ozyx commented on src/plugins/persistence/couch/README.md
> +- 'additionalNamespaces': Other namespaces that this plugin should respond to requests for.
```suggestion
- `additionalNamespaces`: Other namespaces that this plugin should respond to requests for.
```
backticks here?

2024-01-26 22:00 UTC, ozyx commented
Found another issue @scottbell . I don't think it should block the PR at this point? It's still possible to add annotations to a domain object in a read-only database. Is that expected?

2024-01-29 10:41 UTC, scottbell commented
> I did find one issue with search, where after the search has completed, the "loading" progress bar is still spinning permanently:

@ozyx Thank you for the review! I wasn't able to reproduce the spinning search thing. Was there anything in the console?

https://github.com/nasa/openmct/assets/9853862/867c7231-18af-4a26-91f8-8ebfd1f0e957

2024-01-29 10:44 UTC, scottbell commented
> Found another issue @scottbell . I don't think it should block the PR at this point? It's still possible to add annotations to a domain object in a read-only database. Is that expected?

@ozyx I think that's fine as long as the `namespaceToSaveAnnotations` property is set to a writable database. I just tested and threw an error `Uncaught (in promise) Object provider does not support saving`, which seems reasonable to me. Note a variation of this was already happening with YAMCS telemetry, which doesn't support saving.

2024-01-29 15:36 UTC, unlikelyzero commented
@scottbell while you're waiting for additional review from Andrew, can you make sure our backup and restore scripts are up to date with this pattern?

2024-01-29 16:20 UTC, scottbell commented
> @scottbell while you're waiting for additional review from Andrew, can you make sure our backup and restore scripts are up to date with this pattern?

@unlikelyzero good idea! I’ll take a look

2024-01-29 20:38 UTC, scottbell commented
> > @scottbell while you're waiting for additional review from Andrew, can you make sure our backup and restore scripts are up to date with this pattern?
> 
> @unlikelyzero good idea! I’ll take a look

@unlikelyzero they seem like they still work, provided you're using the default db name of `openmct`, but that's always been the case.

2024-01-30 16:30 UTC, akhenry requested changes
This looks great, thank you. My only request is that for consistency with the default namespace we remove the logic to create the root if it doesn't exist. Users can install My Items for additional namespaces if they desire, and the `omitRoot` logic might be confusing.

2024-01-30 16:30 UTC, akhenry commented on src/plugins/persistence/couch/CouchObjectProvider.js
> +  async getOrCreateRoot(identifier, abortSignal) {
Is this a private function?

2024-01-30 16:30 UTC, akhenry commented on src/plugins/persistence/couch/CouchObjectProvider.js
> +  readyGetForBatch(identifier, abortSignal) {
Is this a private function?

2024-01-30 16:30 UTC, akhenry commented on src/plugins/persistence/couch/plugin.js
> +          additionalNamespaces: [LEGACY_SPACE],
chef's kiss 🤌

2024-01-30 16:30 UTC, akhenry commented on src/plugins/persistence/couch/plugin.js
> +    normalizedOptions.databases.forEach((databaseConfiguration) => {
Love it

2024-01-30 16:45 UTC, scottbell commented on src/plugins/persistence/couch/CouchObjectProvider.js
> +  async getOrCreateRoot(identifier, abortSignal) {
it should be!

2024-01-30 16:45 UTC, scottbell commented on src/plugins/persistence/couch/CouchObjectProvider.js
> +  readyGetForBatch(identifier, abortSignal) {
it should be!

2024-01-30 22:40 UTC, akhenry commented on .cspell.json
> +    "unnnormalized",
I'm prepared to accept unnormalized at a stretch. But unnnormalized? With three n's?

2024-01-30 22:52 UTC, akhenry approved these changes

2024-01-30 23:10 UTC, merged