Filter values as a string not an object
nasa/openmct pull request #7448
Opened 2024-01-31 23:11 UTC by shefalijoshi

Closes #7389 

### Describe your changes:
Use the value of a property for filtering metadata as a string if it is not undefined.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Has this been smoke tested?
* [ ] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [ ] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2024-02-01 15:04 UTC, scottbell commented
I'm not sure how to test this given the instructions on the ticket. Is `Duration` metadata? If so, it doesn't appear to be functioning correctly. I tried entering as 15:
<img width="549" alt="Screenshot 2024-02-01 at 3 58 17 PM" src="https://github.com/nasa/openmct/assets/9853862/9736eb2a-f48c-4c22-9ae1-f1fa93768c54">

which rendered no items:
<img width="524" alt="Screenshot 2024-02-01 at 3 58 27 PM" src="https://github.com/nasa/openmct/assets/9853862/c154ecea-1d15-40c3-8e50-339ddb9504a4">

Putting in the exact duration didn't seem to work either:
<img width="363" alt="Screenshot 2024-02-01 at 3 56 58 PM" src="https://github.com/nasa/openmct/assets/9853862/2726f0bc-84b3-41dd-aecf-2ba657be1b54">

One other confusing thing: In edit mode, the time conductor bounds seem to be ignored? It makes adding filters rather confusing:

https://github.com/nasa/openmct/assets/9853862/c8c19739-ca85-41ea-8c6e-7509a7c61725

2024-02-01 15:05 UTC, scottbell requested changes
Having trouble testing this. We should make the testing instructions more clear with images, or a video. Also, we should add an e2e test.

2024-02-01 19:31 UTC, shefalijoshi commented
We have a unit test for this already. We can add e2e test later.

2024-02-01 19:37 UTC, shefalijoshi commented
> I'm not sure how to test this given the instructions on the ticket. Is `Duration` metadata? If so, it doesn't appear to be functioning correctly. I tried entering as 15: <img alt="Screenshot 2024-02-01 at 3 58 17 PM" width="549" src="https://private-user-images.githubusercontent.com/9853862/301546662-9736eb2a-f48c-4c22-9ae1-f1fa93768c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTYxODQsIm5iZiI6MTcwNjgxNTg4NCwicGF0aCI6Ii85ODUzODYyLzMwMTU0NjY2Mi05NzM2ZWIyYS1mNDhjLTRjMjItOWFlMS1mMWZhOTM3NjhjNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTkzMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU5ZGFkNDJlZjA4ZThmZDQzOWFmNTZiYmY5NTc4NWQyNGEwYjQwZDYxNTc5ODZhNDIxMjVkODVkOTgxODdhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Q3oufW1-HPutB1IhTOfjMzPNleHyE63wd_GoSbIAps">
> 
> which rendered no items: <img alt="Screenshot 2024-02-01 at 3 58 27 PM" width="524" src="https://private-user-images.githubusercontent.com/9853862/301546729-c154ecea-1d15-40c3-8e50-339ddb9504a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTYxODQsIm5iZiI6MTcwNjgxNTg4NCwicGF0aCI6Ii85ODUzODYyLzMwMTU0NjcyOS1jMTU0ZWNlYS0xZDE1LTQwYzMtOGU1MC0zMzlkZGI5NTA0YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTkzMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU1NTJlNWQ5ODNiYzU2ZTkyMGY4NzcxNTE1ZjI0Y2ViNGRkYTg2NzdiYjBiYWZhMTk5Njg5NzQ2ZTM0MzA3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5DVR94EvJOhian80CZK3iWnTq0yntIXxv1vFxfk5BAU">
> 
> Putting in the exact duration didn't seem to work either: <img alt="Screenshot 2024-02-01 at 3 56 58 PM" width="363" src="https://private-user-images.githubusercontent.com/9853862/301546835-2726f0bc-84b3-41dd-aecf-2ba657be1b54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTYxODQsIm5iZiI6MTcwNjgxNTg4NCwicGF0aCI6Ii85ODUzODYyLzMwMTU0NjgzNS0yNzI2ZjBiYy04NGIzLTQxZGQtYWVjZi0yYmE2NTdiZTFiNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTkzMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzczYzY5OGRhOWYwOWQzOTg2YzlkNWQ3MjdlMWM4MmYwNzk3YWY2YjNjNTI1YzFkZTFiNjE4M2NlNzE1ODBjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WckYT2KMhJ3urZeuRwGicIwUcV_jH34SKz0SX-pZccs">
> 
> One other confusing thing: In edit mode, the time conductor bounds seem to be ignored? It makes adding filters rather confusing:
> Screen.Recording.2024-02-01.at.4.03.57.PM.mov

Duration can be metadata if you define it in the sourcemap or if it is part of an activity's property like this:
`activity: {properties: {duration: 15}}`

One other confusing thing: In edit mode, the time conductor bounds seem to be ignored? It makes adding filters rather confusing: This is working as designed.

We have a unit test for this already. We can add e2e test later.

I've added documentation for sourceMaps is here: fix-filter-metadata

2024-02-02 12:47 UTC, scottbell commented
Filtering on activities and with commas appeared to work:
<img width="1453" alt="Screenshot 2024-02-02 at 1 41 38 PM" src="https://github.com/nasa/openmct/assets/9853862/0cd1610e-3e80-4d5b-a1e8-4e6c377724df">

as does meta-filtering:
<img width="1453" alt="Screenshot 2024-02-02 at 1 41 47 PM" src="https://github.com/nasa/openmct/assets/9853862/ff086105-944b-49be-88c2-c57febdc9750">
<img width="1453" alt="Screenshot 2024-02-02 at 1 42 48 PM" src="https://github.com/nasa/openmct/assets/9853862/5e2b68ad-dd74-457c-a96a-9c455a0e0342">

with both filters in use, are they supposed to be OR'd together? That looks like the current implementation:
<img width="1767" alt="Screenshot 2024-02-02 at 1 44 51 PM" src="https://github.com/nasa/openmct/assets/9853862/f58d99f3-9327-4c4d-9723-afbef850ecef">

Also, PR doesn't look like it addresses @charlesh88's other issues, in particular:
>We can't filter on values with "." in them - why not? If the user is trying to filter on a decimal number, they won't be able to.
The error messaging for the input is very poor and provides no concrete feedback of what the problem is or how to address it. This needs to be addressed from a text and layout standpoint.

<img width="361" alt="Screenshot 2024-02-02 at 1 46 44 PM" src="https://github.com/nasa/openmct/assets/9853862/0c8e17da-7c4c-4b39-9921-fc5e252ed44c">

2024-02-02 12:48 UTC, scottbell commented on src/plugins/plan/util.js
> +            if (value !== undefined) {
can this ever be null? should that be checked too?

2024-02-02 18:34 UTC, scottbell commented
Looks like one can enter `.` now in filters too:
<img width="187" alt="image" src="https://github.com/nasa/openmct/assets/9853862/8f631c10-ab26-4c76-8c55-7c95c14d3202">

2024-02-02 18:35 UTC, scottbell approved these changes
LGTM

2024-02-05 18:38 UTC, merged