[Mobile] Center Confirmation Dialog Texts
nasa/openmct pull request #7492
Opened 2024-02-09 00:55 UTC by rukmini-bose

Closes  https://github.com/nasa/openmct/issues/7347
### Describe your changes:

- Add code to classes that are used for _only_ confirmation dialogs such that the text and buttons for such messages are centered, rather than floating to the top. This will improve overall mobile UX. 
### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Has this been smoke tested?
* [ ] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [ ] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2024-02-14 17:28 UTC, ozyx commented
Is this visual change covered by any visual tests?

2024-02-22 23:10 UTC, charlesh88 requested changes
I'm finding the button centering is ending up with some unfortunate vertical alignments: 
![Screenshot 2024-02-22 at 2 51 41 PM](https://github.com/nasa/openmct/assets/1056412/18750a3e-879c-48cc-97f8-113880511e23)

I think it'd be better to do a right-alignment, and more consistent with the desktop layout: 

![Screenshot 2024-02-22 at 2 53 13 PM](https://github.com/nasa/openmct/assets/1056412/b2c220dc-8f84-4d28-b69a-1b6b91b6dadf)

2024-02-29 00:48 UTC, unlikelyzero commented on e2e/playwright-mobile.config.js
> -const NUM_WORKERS = 2;
driveby: reduce test flakiness

2024-02-29 01:05 UTC, ozyx commented on e2e/playwright-mobile.config.js
> -const NUM_WORKERS = 2;
nice. yeah 1 should be enough here

2024-02-29 17:44 UTC, ozyx approved these changes
LGTM, just one small non blocking suggestion

2024-03-01 01:23 UTC, charlesh88 approved these changes
After finding some newly introduced issues, have pushed up new changes to address. With that, LGTM.

2024-03-01 22:03 UTC, charlesh88 commented
Problem related to extra margin being introduced to view large/preview/properties dialogs _should_ be fixed. Visual tests should now pass...

2024-03-03 15:57 UTC, unlikelyzero approved these changes

2024-03-03 16:14 UTC, merged