Mct7476
nasa/openmct pull request #7565
Opened 2024-03-07 22:57 UTC by jvigliotta

Closes #7476

### Describe your changes:

Modified Stacked Plots to not show Missing Objects. Added a check in Telemetry Collections for missing objects before displaying telemetry metadata time system error.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2024-03-07 23:31 UTC, jvigliotta commented on .webpack/webpack.prod.js
> +  devtool: 'eval-source-map'
oh dang, didn't push that removal

2024-03-07 23:31 UTC, jvigliotta commented on .webpack/webpack.prod.js
> +  devtool: 'eval-source-map'
should be good now

2024-03-08 02:02 UTC, unlikelyzero approved these changes

2024-03-08 02:57 UTC, ozyx requested changes
Blocking for now will elaborate later but I have a good reason I swear

2024-03-08 18:53 UTC, jvigliotta commented on src/plugins/plot/stackedPlot/StackedPlot.vue
> +      if (!this.openmct.objects.isMissing(child)) {
Haha, it's nuts this got through, not sure how I missed this in the smoke test, nice catch!

2024-03-08 18:57 UTC, jvigliotta commented on src/plugins/plot/stackedPlot/StackedPlotItem.vue
> +      } else if (!this.openmct.objects.isMissing(plotObject)) {
Yep, I like that, will do.

2024-03-12 17:51 UTC, ozyx approved these changes
LGTM

2024-03-14 16:05 UTC, merged