chore(cspell): grammar fixes
nasa/openmct pull request #7735
Opened 2024-05-21 16:41 UTC by evenstensberg

Closes 

### Describe your changes:

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Has this been smoke tested?
* [ ] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [ ] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2024-05-21 16:45 UTC, ozyx commented on .cspell.json
> +    "evaluate",
we can just remove these altogether, no? since they should be included in one of the dictionaries we're using for cspell

2024-05-26 19:35 UTC, evenstensberg commented
@ozyx I want to hand over this PR to you. There's variables in the source code that needs to be changed, and I think that someone that's working with the code actively should make sure the "meta" logic is intact

2024-05-30 16:52 UTC, ozyx commented
> @ozyx I want to hand over this PR to you. There's variables in the source code that needs to be changed, and I think that someone that's working with the code actively should make sure the "meta" logic is intact

You can go ahead and change it and we can catch it in the code review. That would work better for us. Thanks again for taking this on!

2024-06-04 16:24 UTC, ozyx requested changes

2024-06-04 16:24 UTC, ozyx commented on src/api/user/UserAPI.js
> +import StoragePersistence from './StoragePersistence.js';
You'll need to rename this file as well

2024-06-04 16:24 UTC, ozyx commented on src/api/user/StoragePersistance.js
Need to fix the typo in the file name as well. You can use `git mv` so that git tracks the change as a rename

2024-06-05 18:56 UTC, ozyx requested changes
Looking good so far, it's almost there! I found a few other typos that should be removed from `cspell.json` and updated in the codebase. I think this should be good to go once those are fixed.

2024-06-05 18:56 UTC, ozyx commented on .cspell.json
>      "configuation",
we should remove this typo also

2024-06-05 18:56 UTC, ozyx commented on .cspell.json
>      "excercised",
remove

2024-06-05 18:56 UTC, ozyx commented on .cspell.json
>      "dismissable",
remove

2024-06-05 18:56 UTC, ozyx commented on e2e/tests/framework/exampleTemplate.e2e.spec.js
> + * made by the Open MCT team. It will also follow our best practises as those evolve. Please use this structure as a _reference_ and clear
let's use the American English version: `practices`

2024-06-05 18:56 UTC, ozyx commented on .cspell.json
Just a few more that should be removed:

- `exploratorily` - exploratory
- `Telemetery` - telemetry
- `pushs` - pushes

2024-06-05 19:04 UTC, evenstensberg commented
Fixed! 😄

2024-06-28 19:25 UTC, evenstensberg commented
@ozyx wanna have a look?

2024-06-28 23:24 UTC, ozyx requested changes
Ok! Just a couple more changes and LGTM

2024-06-28 23:24 UTC, ozyx commented on .cspell.json
> +    "exploratory",
we can remove this as it's a valid spelling

2024-06-28 23:24 UTC, ozyx commented on .cspell.json
> +    "telemetry",
we can remove this

2024-06-28 23:24 UTC, ozyx commented on .cspell.json
> +    "pushes",
we can remove this

2024-06-28 23:24 UTC, ozyx commented on src/api/telemetry/TelemetryAPISpec.js
> +describe('telemetry', () => {
Capitalize this

2024-06-29 13:06 UTC, evenstensberg commented
PTAL @ozyx

2024-07-01 17:38 UTC, ozyx approved these changes
Nice work! LGTM

2024-07-01 17:38 UTC, merged