fix(package.json): consistent props
nasa/openmct pull request #7768
Opened 2024-07-02 21:14 UTC by evenstensberg

### Describe your changes:
package.json in e2e and root metadata should be identical.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Has this been smoke tested?
* [ ] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [ ] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2024-07-10 20:31 UTC, evenstensberg commented
@ozyx lmk if there's anything I need to do before it is mergeable :)

2024-07-10 20:42 UTC, ozyx commented
> @ozyx lmk if there's anything I need to do before it is mergeable :)

Thanks @evenstensberg ! Really appreciate your patience with us. I'll have a look this afternoon. Cheers

2024-07-10 20:46 UTC, evenstensberg commented
🌟

2024-07-10 22:08 UTC, ozyx requested changes
One small change requested

2024-07-10 22:08 UTC, ozyx commented on e2e/package.json
> +  "homepage": "https://github.com/nasa/openmct/tree/master/e2e",
let's remove the `homepage` prop since this is our e2e testing framework and it will not be served

2024-07-11 20:52 UTC, ozyx approved these changes
LGTM, thanks!

2024-07-15 22:09 UTC, merged