fix(conditional styling): conditional visibility for images and alpha-numerics in display layouts
nasa/openmct pull request #7824
Opened 2024-09-04 18:25 UTC by ozyx

Closes #7718
Closes #7782 

### Describe your changes:

Properly applies the `.is-style-invisible` class to image views and alpha-numeric views within display layouts when visibility is toggled via a conditional style.

Adds a couple regression tests plus a test which generates a localstorage state with a basic condition set that can be used in other e2e tests to save execution time.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2024-09-05 08:07 UTC, scottbell requested changes
Looking good, but I had trouble with the testing instructions in #7782 unless I added some optional chaining [here](https://github.com/nasa/openmct/blob/mct7718-conditional-styling-visibility-option-on-conditional-styling-is-broken/src/plugins/displayLayout/components/TelemetryView.vue#L49) and [here](https://github.com/nasa/openmct/blob/mct7718-conditional-styling-visibility-option-on-conditional-styling-is-broken/src/plugins/displayLayout/components/TelemetryView.vue#L51) as it appeared the domain object was null:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at eval (TelemetryView.vue:49:75)
```

After the optional chaining changes, I could test without issue.

https://github.com/user-attachments/assets/6a0a7b6f-baca-412e-a13f-ea3fbce37139

2024-09-05 16:27 UTC, ozyx commented on e2e/tests/functional/plugins/styling/conditional/displayLayoutConditionalStyling.e2e.spec.js
> +const RICK_JPG =
it's not, but you bring up a good point. I'm thinking i'll go with the base64 image instead.

2024-09-05 17:08 UTC, scottbell commented on e2e/tests/functional/plugins/styling/conditional/displayLayoutConditionalStyling.e2e.spec.js
> +const RICK_JPG =
If there's already precedent, I'm fine either way.

2024-09-06 08:08 UTC, scottbell approved these changes
Works great - well done!

2024-09-06 17:18 UTC, ozyx commented
Waiting to merge this due due an anomaly i found in the visual tests related to me changing a div to a button element. investigating

2024-09-09 22:41 UTC, merged