fix vue reactivity of rows by changing the reference of the updated row
nasa/openmct pull request #7940
Opened 2024-12-03 00:40 UTC by davetsay

Closes #7938 

### Describe your changes:
* make in place row updates trigger vue reactivity
* do not trigger row update calculations on horizontal scroll

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2024-12-04 03:57 UTC, akhenry requested changes
Just wondering whether the `splice` change by itself fixes it?

2024-12-04 03:57 UTC, akhenry commented on src/plugins/telemetryTable/collections/TableRowCollection.js
> -    this.rows[index] = foundRow;
🤦 _this_ is [why reactivity was broken](https://vuejs.org/guide/essentials/list.html#mutation-methods). Good catch!

2024-12-04 04:48 UTC, davetsay commented
> Just wondering whether the `splice` change by itself fixes it?
> 
> Also, can you explain the scrollX issue? Is it related to in-place row updates? The scope of change approved by the CCB is for fixing in-place row updates.

The incoming vs existing is more slimming the code down. We create new `TelemetryTableRow`s, so their datum is already normalized, etc, so we don't have to re-perform that operation. So, updateWithDatum being slimmed down is just a code improvement. Splice vs index replacement is not entirely it. You can index replace with a reference to a new row to trigger reactivity.

The horizontal scroll I came across when I started wondering if throttled calls was affecting adding rows and updating rows. We are calling `updateView` and recalculating `visibleRows` on every vertical AND horizontal scroll. It's unnecessary on horizontal scroll, but can remove if you feel it introduces too much risk.

2024-12-04 19:27 UTC, akhenry approved these changes

2024-12-04 19:27 UTC, merged

2026-07-23 06:52 UTC, RadotJar commented on src/plugins/telemetryTable/collections/TableRowCollection.js
> +    incomingRow.updateWithDatum(existingRow);
Shouldn't this be the other way around? As far as I understand, the intent of the code is to update the existingRow with the new data in incomingRow. This looks to me to do the opposite: Preserving as much of existingRow as possible.