Independent time conductor related handling for plot synchronization.
nasa/openmct pull request #7956
Opened 2024-12-11 21:16 UTC by shefalijoshi

Closes #7737

### Describe your changes:
Ensure that the mode set when independent time conductor is enabled/disabled is propagated correctly.

Also ensure that global time conductor changes are not picked up by the independent time conductor when the user has enabled it at least once before

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Has this been smoke tested?
* [ ] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [ ] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2024-12-17 20:44 UTC, unlikelyzero commented
@shefalijoshi i think the best test is the first example of steps to reproduce:

> No fixed time change warning prompt
> 
> Create an overlay plot, add telemetry to it, and save
> View the plot in realtime mode
> hover over the plot and click Pause
> hover over the plot and click Synchronize with Time Conductor
> Observe you get a warning message and are switched to Fixed time mode (This is expected behavior)
> Toggle the independent time conductor, then toggle the indepedent time conductor off
> Change the time conductor back to realtime mode.
> Repeat steps 4 and 5 to pause and sync time with conductor
> Observe this time there is no warning message.

2024-12-27 19:28 UTC, davetsay requested changes
Looks good. I have a couple requests. One is inline, and the other is can you add test coverage?

2024-12-27 19:28 UTC, davetsay commented on src/api/time/TimeAPI.js
> +      JSON.parse(JSON.stringify(timeContext.getMode()))
I think we can use `structuredClone` over `JSON` cloning, unless there is a good reason not to.

2025-01-29 00:41 UTC, davetsay requested changes

2025-01-29 00:41 UTC, davetsay commented on e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js
> +    // Toggle independent time conductor OFF
Before toggling independent time conductor off we need to ensure it is in fixed mode. If both the global time conductor and independent time conductor modes are realtime, you won't see this bug symptom, even without the bug fix.

2025-01-29 18:16 UTC, shefalijoshi commented on e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js
> +    // Toggle independent time conductor OFF
Good point. Done.

2025-01-29 20:08 UTC, davetsay approved these changes
Awesome. Thanks for perfecting the test.

2025-01-29 20:08 UTC, davetsay commented
Some tests failing however. Hopefully flake...

2025-02-10 21:46 UTC, merged