Discrete Event Visualization in Timeline
nasa/openmct pull request #7967
Opened 2024-12-18 09:23 UTC by scottbell

Closes #7936 

### Describe your changes:

Adds a discrete event visualization for the Time Strip object.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Has this been smoke tested?
* [ ] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [ ] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

2024-12-24 21:54 UTC, unlikelyzero commented on index.html
> +      openmct.install(openmct.plugins.EventTimestripPlugin(timeLinePlugin.extendedLinesBus));
we need to decide if we want this to be the default plugin in core. Traditionally, we don't add new plugins for e2e tests and run the `addInitScript` to add the plugin at runtime.

2024-12-24 21:54 UTC, unlikelyzero commented on e2e/tests/functional/plugins/event/eventTimelineView.e2e.spec.js
> +    await expect(eventWrappers).toHaveCount(expectedEventWrappersCount);
this is great

2024-12-24 21:56 UTC, unlikelyzero commented on e2e/tests/functional/planning/ganttChart.e2e.spec.js
> +    expect(await page.locator('.c-swimlane.is-status--draft').count()).toBe(
why was this change necessary?

2024-12-24 21:57 UTC, unlikelyzero commented on e2e/tests/functional/plugins/event/eventTimelineView.e2e.spec.js
> +      .getByLabel(eventTimelineView.name)
this first step in the chainable _shouldn't_ be necessary

2024-12-24 21:58 UTC, unlikelyzero requested changes
Looks amazing. We should determine if we want this to be the default plugin and included as a notable change in the release notes

2025-01-06 08:30 UTC, scottbell commented on e2e/tests/functional/planning/ganttChart.e2e.spec.js
> +    expect(await page.locator('.c-swimlane.is-status--draft').count()).toBe(
that's a @charlesh88 question

2025-01-06 08:32 UTC, scottbell commented on index.html
> +      openmct.install(openmct.plugins.EventTimestripPlugin(timeLinePlugin.extendedLinesBus));
ok, will defer this to @charlesh88 or @akhenry

2025-01-14 17:18 UTC, charlesh88 commented on e2e/tests/functional/planning/ganttChart.e2e.spec.js
> +    expect(await page.locator('.c-swimlane.is-status--draft').count()).toBe(
`.u-contents` as a class is superfluous in that context. The CSS class is being used as a selector for the test; `.c-swimlane.is-status--draft` is more than sufficient and less brittle.

2025-02-27 02:03 UTC, akhenry requested changes

2025-03-04 17:32 UTC, shefalijoshi submitted a review, later dismissed

2025-03-05 18:19 UTC, shefalijoshi commented on src/plugins/imagery/ImageryTimestripViewProvider.js
> +      return 7000; // big number!
Changed this to use the priority API, but it's still set to 7000. Need to see why it needs to be so high.

2025-03-05 18:47 UTC, shefalijoshi commented on src/plugins/events/components/EventTimelineView.vue
> +        this.updateViewBounds();
Changed this to call `this.setScaleAndPlotEvents(this.timeSystem)` instead.

2025-03-06 00:19 UTC, shefalijoshi commented on src/plugins/events/components/EventTimelineView.vue
> +              !this.isEventInBounds({
No longer looking at bounds in here.

2025-03-06 00:20 UTC, shefalijoshi commented on src/plugins/events/components/EventTimelineView.vue
> +        eventWrapper.addEventListener('mouseover', () => {
Done

2025-03-06 00:21 UTC, shefalijoshi commented on src/api/tooltips/ToolTipAPI.js
> +   * Tooltips take an options object that consists of the string, tooltipLocation, a parentElement, and an array of cssClasses
Done

2025-03-07 10:19 UTC, scottbell commented on src/plugins/events/components/EventTimelineView.vue
> +        //this is a hack - need a better way to find the parent of this component
Braindead copy/paste from [PlanView](https://github.com/nasa/openmct/blob/master/src/plugins/plan/components/PlanView.vue#L292). Now using `$el`

2025-03-07 11:02 UTC, scottbell commented on src/plugins/timeline/ExtendedLinesBus.js
> +export default class ExtendedLinesBus extends EventEmitter {
Gave it a shot! Let me know what you think.

2025-03-07 12:15 UTC, scottbell commented on src/plugins/timeline/ExtendedLinesBus.js
> +export default class ExtendedLinesBus extends EventEmitter {
We [pass this bus around](https://github.com/nasa/openmct/blob/8545ddeaff4f406c21a6539a3ceb53322ebe329a/index.html#L238) between two Open MCT plugins, the timeline plugin, and the events plugin, so on first blush I'd probably say it's better as a plain ES6 class.

2025-03-07 17:01 UTC, shefalijoshi commented on src/plugins/events/components/EventTimelineView.vue
> +      const events = this.$el.querySelectorAll(`.${EVENT_WRAPPER_CLASS}`);
With the refactor I don't think this is an issue anymore.

2025-03-07 17:07 UTC, shefalijoshi commented on src/plugins/events/components/EventTimelineView.vue
> +        // Fallback: use the actual container element (the immediate parent)
I vaguely recall `.parentElement` not working in some specific cases for planView, but maybe that's not an issue here. I'll test.

2025-04-21 18:26 UTC, akhenry requested changes

2025-04-21 18:26 UTC, akhenry commented on src/plugins/plan/components/ActivityTimeline.vue
> +      return '100%'; // TEMP!
@charlesh88 ?

2025-04-21 19:10 UTC, charlesh88 commented on src/plugins/plan/components/ActivityTimeline.vue
> +      return '100%'; // TEMP!
Whoops, apologies. Removed commented and obsolete code.

2025-04-21 19:45 UTC, scottbell commented on src/plugins/events/components/EventTimelineView.vue
> +    createSelectionForInspector(event, eventWrapper) {
Lost write permission to this branch 😢, but the fix should look like this:
```js
createSelectionForInspector(event) {
      const eventWrapper = this.$refs[`wrapper-${event.time}`][0];
      const eventContext = {
        type: 'time-strip-event-selection',
        event,
        item: this.domainObject
      };

      this.unsubscribeSelection = this.openmct.selection.selectable(
        eventWrapper,
        eventContext,
        true
      );
    },
```

2025-04-21 19:46 UTC, scottbell commented on src/plugins/events/components/EventTimelineView.vue
> +    createSelectionForInspector(event, eventWrapper) {
And in `beforeUnmount`:
```js
if (this.unsubscribeSelection) {
    this.unsubscribeSelection();
}
```

2025-07-26 00:44 UTC, merged